### ISSUE TITLE
Feature Request - Control fans based on workload

### ISSUE THREAD

**Issue by DE8468** [Rem0o/FanControl.Releases#10]
Can the fan speed be controlled according to the load, such as CPU Power, GPU Power?
Thanks

**Comment by Rem0o** [comment]
Well it could, but why would you? 

You ain't cooling power, but temperature, no? Since power figures will go up and down real fast and the internal clock of the software is 1 Hz, the power figure might go from 90% to 0% then 100% back again, which won't be a good target for a fan curve. Temperature is already kind of a "smoothed" version of the power figure, or more like a integral of the power over time.

**Comment by DE8468** [comment]
I understand
