### ISSUE TITLE
Why it starts rasman.dll(Remote Access Server Manager library)?

### ISSUE THREAD

**Issue by antoan-boss** [Rem0o/FanControl.Releases#101]
I found it started rasman.dll!RasSignalMonitor... in threads when I checked Process Explorer. By google search rasman.dll is Remote Access Server Manager library. There is not source code here, so I can't check why... Kinda suspicious?

![rasman](https://user-images.githubusercontent.com/9251344/103275726-15ea6580-49c5-11eb-9c20-254ef34cbd8a.png)

**Comment by Rem0o** [comment]
Well, I have seriously no idea why it would access that DLL. The only networking the app does is to check if there is a new version available by pinging this file https://github.com/Rem0o/FanControl.Releases/blob/master/version.json, but this has nothing to do with remote access. Monitored my own instance for a bit and got nothing similar 
![image](https://user-images.githubusercontent.com/14118956/103296139-78426680-49c3-11eb-9fb5-7fa95e30689f.png)

All the DLL I'm using are common packages or open source projects. Now for the exe itself, have fun decompiling it if you want to get in there and try to find something suspicious, you won't. I'm keeping it closed source because I run this as a donationware, but there is no magic to this app, it's just a LibreHardwareMonitor UI / overlay. Anyone can start from LibreHardwareMonitorLib and build something with similar functionalities.

**Comment by mhartvig** [comment]
In process explorer you need to go into File -> Show details for all process... for it to show up, but it's there.

**Comment by antoan-boss** [comment]
Also I don't see it there every time. I'm just curious if someone has answer why??

**Comment by marcellarius** [comment]
I don't think it's nefarious. I've experimented a bit, and I suspect it's some kind of side effect of Process Explorer hooking into the CLR.

The rasman.dll thread appears if I display the FanControl UI window, then inspect process from Process Explorer, then close then reopen the Properties window. The thread appears as a side effect of disconnecting from the process.

It seems very likely that it's just a .NET/WPF debugging quirk, leaving a thread running when the debugger detaches.
