### ISSUE TITLE
The "Control from external source" still pops up after uninstalling Armoury Crate 

### ISSUE THREAD

**Issue by RapidJamer** [Rem0o/FanControl.Releases#1012]
So the external source "?" still pops up after i deleted Armoury Crate and i dont know why and also my other 2 fans are still non responsive when i manually control 'em. Any fixes or anything on it that may help?

*Tried Armoury Crate fan settings and regardless of what i do, the fan settings are never there nor show up. Also need some help on solving that 😐😐*

**Comment by WolfspiritM** [comment]
I think I found the reason in my case. It seems like updating armoury crate caused it to automaticly enable "FanXpert" and also "AI Cooling". While I disabled FanXpert via Armoury crate prior to disabling the services, it seems like that doesn't disable "AI Cooling". I now booted into UEFI (BIOS) and disabled AI Cooling. Now Fan Control seems to have no issues anymore.

When it comes to the non responsive fans. Did they work before? I had cases where "Auto Detect" didn't work for the Fan mode and I had to manually select the mode (either PWM or DC) otherwise they'd spin at full speed.

**Comment by RapidJamer** [comment]
The fans did work especially Auto detect until something happened while i was away on a trip for a few weeks. I came back and fan control had an update then i noticed that all but one of my fans were actually manually responsive. 

Also, where did you find fanexpert? ive never seen any fan controls or anything fan related on Armoury Crate

**Comment by WolfspiritM** [comment]
As far as I remember In my case it's under the second tab where I could choose between my motherboard and fan xpert. This however might depend on the mainboard. Armoury Crate doesn't open anymore since I disabled all services so I can't say for sure. But I'm sure you can disable it in the UEFI aswell.
