### ISSUE TITLE
Feature Request: Add a math custom sensor.

### ISSUE THREAD

**Issue by VanStorm** [Rem0o/FanControl.Releases#1093]
Basically the idea would be to have a custom sensor similar to the mix custom sensor except one could select one sensor and then add/substract a constant value from the sensor or multiply the temperature with a constant.

Why would this be useful?
It would allow for example to adjust the value of an external sensor that is not accurate or help to quickly adjust the value used for a fan graph without actually having to redraw it.

**Comment by Rem0o** [comment]
I fail to see this as a solution to the problems you mentionned.

> It would allow for example to adjust the value of an external sensor that is not accurate
 
Heh... example? Why not simply draw the graph arround that sensor, or maybe I should add a new option in sensor settings, like with nicknames, to adjust a sensor offset directly.  Having to create a new sensor to wrap the old bad sensor seems like a janky solution.

> quickly adjust the value used for a fan graph without actually having to redraw it.

I would add a tool to offset a graph all at once, like dragging the line of the graph, instead of changing the sensor.

**Comment by VanStorm** [comment]
Yeah an offset directly on the sensor would be great. Either like by adding a constant or by multiplication.

Or being able to move the whole graph would solve it as well. Although the first thing would be better in my opinion.

**Comment by ItsMeAubey** [comment]
But there is already a mix custom sensor, no? Just add a "file" sensor, put your offset there, then do math in the mix sensor.

**Comment by Rem0o** [comment]
^ This, while not very elegant, will work.

**Comment by VanStorm** [comment]
Ty for that suggestion that helps indeed as an additive offset without having to redraw the graph.

**Comment by foreachthing** [comment]
I was looking for a multiplier ... how could this be achieved?
`FrontCaseFanSpeed = max(GPU, CPU) * f`
