### ISSUE TITLE
Temperature from HWINFO plugin stops syncing

### ISSUE THREAD

**Issue by RRRRRRRAA** [Rem0o/FanControl.Releases#1123]
Hello,
1.I love your software,it is amazingly powerful :3 
2. I have this issue with sensor detection. i have a WTEMP sensor i my waterloop, and it is not visible by fan control, but hwinfo can see it as T_Sensor. So i set up the plugin with 30 sec startup delay and it works flawlessly. But after 10 minutes or so the sensor value in fan control freezes while the HWINFO value goes on. It is quite dangerous, since I have zero rpm in low water temp and when it freezes the fans fail to start which causes water overheat. Fan control throws an unexpected error or missing sensor. It is in the log file. I am committed to donating a bit when this is resolved, because i will be using only fan control from now on. I wrote that not to push my issue, but as a simple Fact :D Thanks!
[log.txt](https://github.com/Rem0o/FanControl.Releases/files/9628051/log.txt)
![image](https://user-images.githubusercontent.com/76033749/191811758-3cd21f71-864a-4a06-a7ee-57f1bb85deba.png)

**Comment by RRRRRRRAA** [comment]
and yes that is a 6MB log file :)

**Comment by DfrostX** [comment]
It`s actually an asus EC sensor issue.

Most Asus EC semsor have very high latency. So high that it somethime does not refresh fast enough between HWinfo pooling period and it  goes missing from the HWinfo list completely since it has not reported during a pooling cycle. When this happen, the plugin will report to Fan Control that the sensor has gone missing.

You can see this in HWinfo if you add the pooling time option to the sensors. Also, you should see the sensor disapearing and coming back in the list of sensors

If that sensor is not the reason, it could be that in your HWinfo list, a sensor above the one you want to report to the plugin goes missing for the same reason I described above. This  situation will change the order of  your sensor list in HWinfo and it seems like the plugin is sensitive to this  (ex. Sensor to read is 20th but now its 19th, but Fan Control expect the value to read in 20th which is now something else).

A couple things to try:

-Increase the pooling time in HWinfo over the pooling time of that sensor to avoid it from vanishing.
-Reoder manuallly the sensor of Hwinfo and put on top the one you want to report to Fan Control so that if one vanishes, it will not affect it.

Honnestly, I use to have the same issue with the Asus EC for my water temp and got fed up of it. I bought an highflow next from Aquatuning, deactivated Asus EC in HWinfo and never used it again. Water Temp reading has been working flawlessly since then and I have a flow meter on top of it... All this in HWinfo since it supports it!

**Comment by DfrostX** [comment]
Related topic

https://github.com/Rem0o/FanControl.HWInfo/issues/29

**Comment by Rem0o** [comment]
Download the latest release of the HwInfo plugin, it should help with fault tolerance.

**Comment by RRRRRRRAA** [comment]
version 130 of fan control, updating the plugin and 3 second refresh rate of hwinfo sensors solved it. Big thanks for the help! Time for my promise then.. :)
