### ISSUE TITLE
Start up doesn't work

### ISSUE THREAD

**Issue by kxi0** [Rem0o/FanControl.Releases#1157]
**Describe the bug**
Windows startup doesn't start FanControl on startup

**Is there a log.txt file next to FanControl.exe with recent date entries?**
no

**Relevant hardware specs and setup**
b450f ii
5600g
gammix s5 256gb

**Comment by Chris8413** [comment]
I am having the same problem, re-installed the software but it doesn't actually install on system. No Fancontrol file, or icon and doesn't start up with my PC. Worked fine 2 days ago.

**Comment by nikolarun** [comment]
I had a similar issue, and had to downgrade to an older version.  if I autoupdate it, it doesn't launch for me at all.
I am on v118 at the moment.

**Comment by WantStuff** [comment]
Same issue for me started with v130 (I think). I'm now on v131.

Checking the Task Scheduler I see:
"Task Scheduler did not launch task "\FanControl" because user "{My Domain}\{My user}" was not logged on when the launching conditions were met. User Action: Ensure user is logged on or change the task definition to allow launching when user is logged off."
I get the same error when I run the Task manually. Running the EXE manually is fine, so the error is def with the Task.
*My PC is part of a Domain if this is relevant

I have tried editing the Task, including ensuring the user account in  "Security Options" is a PC and Domain admin, but I still see the above.
If I change the service to "Run whether the user is logged on or not" it does not error but (obvs) starts before I am logged in.

**Comment by nikolarun** [comment]
The new version has resolved my issue ( 131 )

**Comment by PsychoManiac189** [comment]
running 134 and still doesn't start up. I just looked in task scheduler and the task is there, but hasn't run yet. so i just clicked properties changed one setting to run even if not logged in and typed in my password. ill let ya know if it works
