### ISSUE TITLE
Startup Task registration works only for administrator user accounts

### ISSUE THREAD

**Issue by NM1r** [Rem0o/FanControl.Releases#12]
If you are logged in as a standard user, the task will only be registered for the admin account used to execute the cmd file.

**Comment by Rem0o** [comment]
But the app needs admin rights to run. How would you run it from that user?

**Comment by NM1r** [comment]
I thought it could be done with the task scheduler, but I havent' t found a way yet. However Argus monitor works for standard users so I guess there is a way to add this functionality to your application.

**Comment by AdrenalinaGit** [comment]
@NM1r:  In the task's General tab, did you try typing the name of an account that has admin rights, into the field labeled "When running the task use the following user account"?

Perhaps you'll find the info you need at the following webpage:  https://superuser.com/questions/656964/what-user-must-a-scheduled-task-run-as-in-order-to-be-visible-for-all-users

I don't have that issue because my pc's only user account (mine) has admin rights.  But one of the things I changed in the task definition was the Action tab, so that instead of launching FanControl indirectly with cmd.exe's START command, the task launches FanControl.exe directly, and with the Action tab's "Start in" field set to the folder where FanControl was installed. (I also unchecked the checkboxes in the Trigger's tab's Trigger and in the Settings tab that would stop the task after 3 days.)

**Comment by NM1r** [comment]
It does not seem possible without having to deal with UAC prompts everytime you log in. Maybe you could outsource the part of your application which requires admin privilege to a service (https://docs.microsoft.com/en-us/dotnet/framework/windows-services/introduction-to-windows-service-applications). However at the moment you should set your app to require admin privilege on launch because otherwise most functions will not work without displaying an error message and sometimes unhandled exceptions will appear.
In general it is not recommended to use an admin account as main account, so solving the problem might be worth the hassle.

**Comment by AdrenalinaGit** [comment]
@NM1r : If the UAC prompt only appears when the user tries to access the FanControl UI by clicking its tray icon, perhaps it's not a serious problem, since the user ordinarily doesn't need to display FanControl once its configuration has been set up correctly.

Assuming the UAC prompts are a serious problem, perhaps an acceptable alternative would be to run FanControl as a background process (no UI visible to the user).  In other words, in the Triggers tab set the task to trigger at Windows Startup instead of when the user logs in, and in the General tab set the task to run with an admin account and whether user is logged in or not.  I don't think I've tested this thoroughly since my pc's user (me) has admin rights, but it ought to be quick for you to test.  If you try it, please let us know the result.  Of course, the user wouldn't be able to edit the FanControl configuration due to the unavailable UI, but the configuration could be prepared in advance by the Admininstrator.  And if the user wants to display fan speeds and temperatures, s/he could run a monitor app (such as HWiNFO or LibreHardwareMonitor).

Since a bad FanControl configuration could cause the hardware to overheat and die young, it's debatable whether a lowly, possibly malicious user should be allowed to access the UI to modify the FanControl configuration.  Maybe running FanControl as a background process is wise.

You said Argus Monitor works okay for a lowly user.  I presume it requires admin rights.  Does it cause UAC prompts?  How does it get launched?  Does it have an associated Windows Task Scheduler task?  Does it have an associated service?

**Comment by Rem0o** [comment]
The task is now embedded into the app itself, which requires elevated privilege anyway. Closing.
