### ISSUE TITLE
NVApiWrapper error on startup. GPU curve is deleted on every startup

### ISSUE THREAD

**Issue by frenzer** [Rem0o/FanControl.Releases#1334]
Since 2 weeks ago I started to get a sensory error every time I start the program.

https://user-images.githubusercontent.com/49452007/205266562-491a3828-72c4-49ca-88f4-026fe25d000a.png

I have set the startup time to 120 seconds and here are my sensor settings
![image](https://user-images.githubusercontent.com/49452007/205266980-b7915cb7-3bc6-42fc-9fab-6df4235c1573.png)

Specs:
GPU - 3080ti Palit

I had Thundermaster installed before and I thought it was causing the issue, however I uninstalled it and there is no change.

Additionally every time I start the program the GPU curve is gone and I have to recreate it and connect it to the sensors. Tried saving the json and loading it but that didn't work.

**Comment by Rem0o** [comment]
Any log.txt?

**Comment by Taudris** [comment]
I had this problem as well and found this in log.txt:

```
12/3/2022 12:38:58 AM: NvAPIWrapper.Native.Exceptions.NVIDIAApiException: NVAPI_NVIDIA_DEVICE_NOT_FOUND
   at NvAPIWrapper.Native.GPUApi.GetThermalSettings(PhysicalGPUHandle physicalGPUHandle, ThermalSettingsTarget sensorTarget)
   at NvAPIWrapper.GPU.GPUThermalInformation.get_ThermalSensors()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiTempSensor.Update()
   at FanControl.Domain.BackendProviders.NVApiWrapper.NVApiWrapperBackendProvider.Update()
12/3/2022 12:39:04 AM: NvAPI failed. A complete refresh is required.
```

I was able to fix my existing configuration by doing the following (these steps only work if you didn't save the configuration while fan curves were missing):
1. Add a new fan curve.
2. Select the NVIDIA temperature sensor.
3. Save the config to a new file.
4. Find the ID value from one of the sensor strings, eg `19968` from this: `NVApiWrapper/19968/sensor/0`
5. Replace the ID value from my config with the new ID value.

What happened before is that the fan curve would remain visible, but with no sensor selected. All I needed to do to fix it was pick the sensor again, and it would work without having to create a new fan curve.

Since the ID that the NVIDIA API uses is not stable over time (it changes with either some or all driver updates), I suggest changing the configuration system's design to select a GPU using data that doesn't change as often.

Serial number is unfortunately not available on NVIDIA's gaming GPUs, but you could use, for example, the GPU name somehow combined with stable attributes such as the number and type of sensors/controls.

Ideas for how the sensor string might look:
* `NVApiWrapper/NVIDIA GeForce RTX 3080/d984e26a/sensor/0` (hash based on whatever attributes might be stable)
* `NVApiWrapper/NVIDIA GeForce RTX 3080/1Thermal2Cooler/sensor/0` (count of each sensor and control type)
* `NVApiWrapper/NVIDIA GeForce RTX 3080/Thermal0_-42_127 Cooler1_30_100 Cooler2_30_100/sensor/0` (The `0`, `1`, and `2` are IDs from the NVApiWrapper. The `_#_#` is the default minimum and maximum. I don't know how stable these are, but maybe they always come from the GPU BIOS.)
* `NVApiWrapper/NVIDIA GeForce RTX 3080 [19968]/d984e26a/sensor/0` if someone has multiple GPUs with the same name and hash. It would help such users to see the `[19968]` in the UI as well. (But multi-GPU may be an edge case that you don't necessarily need to solve nicely.)

**Comment by Rem0o** [comment]
@Taudris  good find with the Id changing over time with driver updates.  The tricky part is to differentiate two of the same GPUs in the same system, like two 1080s.

I think I might get away with the index of the GPU, (0 for the first, 1 for the second....) and the codename of the architecture, like GP106-A for a 1060, something like 0-GP106-A for a single 1060.  I don't expect people to swap PCI-E slot of their GPUs that often.

**Comment by Taudris** [comment]
I didn't see the hardware ID when I was poking around in the NV wrapper sample app, which is why I was suggesting using those other attributes. But maybe the sample just doesn't show it, or I missed it, or maybe you can connect the two by looking somewhere in the registry. If you can figure out a way, then that should be a great solution.

**Comment by Rem0o** [comment]
^ There is no hardware id, can confirm.

**Comment by frenzer** [comment]
> 

04-Dec-22 6:50:25 PM: System.Exception: Could not create instance of FanControl.Plugins.IPlugin2
   at FanControl.Domain.PluginService.CreateInstance[T](Type type)
   at FanControl.Domain.PluginService.LoadTypes[T](Assembly assembly)

Thats all there is on the log_1.txt

I will try what Taudris suggested.

**Comment by Taudris** [comment]
@Rem0o This was bugging me, so I looked a little deeper, and it turns out that NvAPIWrapper *does* provide hardware IDs. This information is not surfaced by the sample app because it prints the `PhysicalGPU` object with `maxDepth=0` (and changing it to `1` causes it to fail, though it does manage to print the bus information).

```
var hardwareId = PhysicalGPU.GetPhysicalGPUs()[0].BusInformation.PCIIdentifiers.ToString();
```

**Comment by Rem0o** [comment]
@Taudris  I guess that could work, but I've settled on the adapter index. Should be reliable enough.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/206738182-2b6d07be-8de1-4ffa-80f4-8d790c700af4.png)

V139 has the new ids in, make sure to save your config when prompted.
