### ISSUE TITLE
Shift only when graph value is greater than zero?

### ISSUE THREAD

**Issue by enchikiben** [Rem0o/FanControl.Releases#1473]
Hello

Is it possible to add to the graph value in the fan? The offset is not suitable, I need the fan to stop when the value in the graph is 0, and if you set the offset, it will not be 0.

I understand that you can make a schedule for each fan, but I don’t want to. Is it possible to make a plugin or something else so that you can select a graph and indent as a parameter and apply this mix to the fan? But so that when the indent works only if the value of the graph is greater than 0.

**Comment by Rem0o** [comment]
Set a stop% to be the same value as the offset?

**Comment by enchikiben** [comment]
I tried it does not help, the problem is that the fan stops when 0 comes to it, if you set offset% or stop%, then they will be sent, not 0.

It is necessary to somehow do offset% when more than zero comes from the graph.

**Comment by enchikiben** [comment]
@Rem0o Is there an opportunity to write plugins for the interface? Adding their functionality.

**Comment by Rem0o** [comment]
^ I'm not sure to understand exactly what you want.  If I understand what you are saying:
>  if you set offset% or stop%, then they will be sent

Sent? 

If I understand correctly, you want to use a graph on a fan, but apply an offset to it. The problem is that the 0% zone of your graph is then also offset, which means the fan will never stop. 

To remedy that, I recommended you set your stop% higher than said offset. Stop% will take any command lower than its % value and snap it to 0, which should stop your fan.

Like this: 
![image](https://user-images.githubusercontent.com/14118956/213715369-6bc8c25b-369a-4005-b309-18cbe67a3801.png)

**Comment by enchikiben** [comment]
You understood correctly, but the problem is that my fan controller stops them when a command is sent to it with 0, and in your example, send 11.

I want the offset to be applied only when the graph is greater than 0, then if the graph is 0 and go to the controller 0 and it will stop the fan.

**Comment by Rem0o** [comment]
Do you understand how stop% works? It won't send 11%, it will send 0% for any command at or below 11.

**Comment by enchikiben** [comment]
Thank you!!! I really did not understand the settings, everything worked as it should!

**Comment by Micodnite** [comment]
I recently just bought the Intel ARC A770 gpu and it is not being detected. Checked HWMonitor and it is there.
