### ISSUE TITLE
[Enhancement] System tray text rendering

### ISSUE THREAD

**Issue by Silther** [Rem0o/FanControl.Releases#1479]
Use a different text rendering engine for the system tray icon, as the temperature display is always pixelated.

![image](https://user-images.githubusercontent.com/97352673/213865740-5132f05d-627e-4dcb-926b-ae718396342f.png)

**Comment by Rem0o** [comment]
Sadly, there is no "different" text rendering engine available. What's your resolution and scaling used ?

I prototyped some DPI-awareness into the icon, but it's not ready yet.

**Comment by xIUPITERx** [comment]
I use a 2560 x 1440 monitor and 125% scaling.

**Comment by Rem0o** [comment]
[DPI-Aware-FanControl.zip](https://github.com/Rem0o/FanControl.Releases/files/10473279/DPI-Aware-FanControl.zip)

If you want, swap these two files into your existing FanControl folder.  Show how the icon look.

**Comment by xIUPITERx** [comment]
It triggered a antivirus warning, but after a quick scan it works perfect.

![image](https://user-images.githubusercontent.com/97352673/213892579-164447d0-6b99-4fbd-add3-d7cb8ce23499.png)

**Comment by Rem0o** [comment]
Sweet.

This will be coming in a future update.

**Comment by xIUPITERx** [comment]
Should I close the issue?

**Comment by Rem0o** [comment]
Yes.

**Comment by xIUPITERx** [comment]
![image](https://user-images.githubusercontent.com/97352673/222274986-dddc6414-aea0-49b4-8624-0f00cf56920c.png)

After the v148 Update the clock with DPI-awareness is broken. 
However, since the function has not yet been officially rolled out and I am still using the version from the ZIP file, I don't know if it is a problem at all.
However, since the updates to 145, 146, 147 worked quite normally and the clock continued to render with DPI-awareness after the updates, I wanted to inform you about this.

**Comment by Rem0o** [comment]
V148 has not made any change regarding the tray icon? Do you run a multi-screen setup?

**Comment by xIUPITERx** [comment]
No, I only have a QHD monitor and nothing has changed.
In the meantime, I have had an Nvidia driver update and a Windows update (2023-02 Cumulative Update for Windows 11 Version 22H2 for x64-based Systems (KB5022913)).
