### ISSUE TITLE
Proportional Offset

### ISSUE THREAD

**Issue by Hyporeal** [Rem0o/FanControl.Releases#1491]
There is a nice feature that allows for an offset that subtracts from the fan speed curve. It would be nice to have an proportional offset relative to another fan speed/fan curve. In other words, it would be multiplicative.

CURRENT OFFSET TYPE:
For example, if FAN A is 100% and FAN B has a -30% offset with the current method, it would be 70%. With this same method, if FAN A was 50%, FAN B with the same off set would be 20%.

PROPORTIONAL:
Let's say in this case, FAN B is set to 70%, relative to FAN A. With a proportional offset FAN A would still be 100% and FAN B would 70%. However, if FAN A was 50%, FAN B would be 35%.

For example, sometimes intake fans are restricted by radiators or there might be more exhaust fans than intake. If FAN A was intake and FAN B was exhaust, this would be useful for maintaining positive air pressure in the case, but still maximizing airflow.

**Comment by Rem0o** [comment]
I would guess you are talking about the "Sync" fan curve right?
![image](https://user-images.githubusercontent.com/14118956/214693300-0efc2471-de8f-46cd-9a06-27f7ffc0a1fc.png)

**Comment by Hyporeal** [comment]
Yes, I believe we are on the same page! I apologize. I should have included a screenshot!

**Comment by Rem0o** [comment]
Something like this 
![image](https://user-images.githubusercontent.com/14118956/214697954-fa0dedbb-31f5-4a5b-9ec7-d2c28519c899.png)

**Comment by Rem0o** [comment]
See V145

**Comment by NeverUsedID** [comment]
Very nice feature :)

**Comment by Hyporeal** [comment]
> Very nice feature :)

Yeah, he was super-fast at responding and implementing that. I donated what I could.

**Comment by joaorsbarbosa** [comment]
At the moment, the "Sync" proportional offset works great, but it only works using FAN speeds. I have to choose a specific fan to which I can create an offset.

Would it be possible to, instead, have the Sync fan curve utilize a fan curve instead of a fan RPM? That is, I would like to have a "sync" proportional offset in relation to an Auto curve.

I know I can create a second Auto curve utilizing the same sensor and create an offset from there but the previous solution seems "cleaner". 

Cheers!
