### ISSUE TITLE
Curves don't work after updating from v147 to v150

### ISSUE THREAD

**Issue by veilside03** [Rem0o/FanControl.Releases#1640]
First of all I've been using this tool since ~ v112, so I exactly know how to use it.
But since I updated the tool from v147 (net6) to v150 (net7), my custom made fan curves don't work.

For testing purposes I created a flat curve with "100% speed" set, then I assigned it for my CPU / GPU / case fans. Nothing happened. Neither applying "Force apply" have any effects. "Manual control" however works fine.

I tried to create a completely new .json file, starting from scratch. Self-test (fan stop, fan start, etc.) works fine. The tool detects all my sensors and fans correctly, manually adjusting fan speeds works fine for all fans, but non of the custom fan curves work.

I already deleted and redownloaded the tool, but no success.

I downloaded v149 again: that works perfectly, custom curves work as intended. But v150 doesn't.

What I've done:
- .NET 7 is installed
- Windows was restarted

**Comment by xasz** [comment]
Having the same problem. Even with Flat Curves.

**Comment by Rem0o** [comment]
Identified the problem: it only affects the flat fan curve, but any curve mix curve implying it will bug, Will push a hotfix.

**Comment by Rem0o** [comment]
V151

**Comment by Rem0o** [comment]
@tinsukE  weird. It's as if you didn't have the V151 change. You might have got stuck in limbo in the file upload on github.   Might run the updater again?

**Comment by zachary52368** [comment]
I'll throw in my 2 cents as someone who had the same issue and say that running the updater again fixed the problem.

**Comment by tinsukE** [comment]
> I'll throw in my 2 cents as someone who had the same issue and say that running the updater again fixed the problem.

Yeah, even though the software reported being 1.51 already, I closed it, ran the updater, and now flat curves load just fine again.

**Comment by robv1306** [comment]
Further info about this issue: despite repeatedly re-installing and even having friends send their setups over, I still get nothing. 

The issue seems to be that none of the fans are seen to "respond" to the self identification process. When the process starts, it simply turns them all down to minimum and they stay there until the process ends. 

As for why the fans are running at the speed they're running, I have no idea. I don't seem to be able to change it in the BIOS and FanControl.exe was the only software I had installed which edited it. Any help would be massively appreciated. My PC is currently borderline unusable. I'm trying my best to give as detailed a description of the issue as I can but if you need anything else, please ask.
