### ISSUE TITLE
[Feature Request]Timed average function 

### ISSUE THREAD

**Issue by Bluedot55** [Rem0o/FanControl.Releases#184]
Would it be possible to add a timed average temperature? This would be really useful for setting indirect fans- things like case fans, radiator fans, etc. They really only need to ramp up if the temp is kept high for long durations, since for example a water loop isn't going to heat up much after 10 seconds of activity. The step up is pretty close, but not quite the same thing.

**Comment by Rem0o** [comment]
What about response time on your curves?  If you set a very long response time, like a minute, it kind of does the same idea. It won't change speed unless the temperature changed significantly for over a minute.

Otherwise, I would see that as a new type of custom sensor, kinda like the "mix" one that already exists. Would be easy to add.

**Comment by trankillity** [comment]
I'm not entirely sure that the "response time" feature is working as expected. It definitely does on temperature decrease, but I've frequently seen my fans spin up using the Target curve type whenever a spike happens. This may be contributing to the desire for this feature.

**Comment by Rem0o** [comment]
See V72
