### ISSUE TITLE
Primary theme color cannot be gray, always switches to red when gray is picked

### ISSUE THREAD

**Issue by lednerg** [Rem0o/FanControl.Releases#1868]
**Describe the bug**
When the "primary" theme color is a neutral gray, Fan Control will always switch to a red color for the Curves cards instead. For this reason, themes can no longer be neutral gray. As far as I know, this is only happening on the Curves cards.

![Fan Control theme Issue](https://github.com/Rem0o/FanControl.Releases/assets/42688498/315e017e-d016-45db-ba29-07470eec041d)

This happened a few updates ago. I'm sorry, but I cannot remember exactly which one it was.

**Is there a log.txt file next to FanControl.exe with recent date entries?**
Nope

**Relevant hardware specs and setup**
Windows 10 Pro

**Comment by Rem0o** [comment]
Good catch.  I calculate the lighter and darker color from the primary color in HSB.  When you convert a gray scale into HSB, the "hue" aspect will default to red. So changing saturation on that red hue will make a dark red color.  Will add an exception when saturation == 0 so that it stays 0 ( gray scale ).

Thanks
