### ISSUE TITLE
An unexpected error has occurred. 

### ISSUE THREAD

**Issue by vitduck** [Rem0o/FanControl.Releases#1924]
**Describe the bug**
This is not a critical bug and Fan Control does not crash. 
The message "An expect error" occurs randomly when adjusting the fan speed. 
An entry in the log file is created indicating an unhandled exception. 

**Is there a log.txt file next to FanControl.exe with recent date entries?**
[error.log](https://github.com/Rem0o/FanControl.Releases/files/12066709/error.log)

**Relevant hardware specs and setup**
OS: W10 22H2 
MB: MSI B550m Mag Mortar 
Fan Control:  v163 

**Temporary workaround** 
Downgrade to 162

**Comment by garethsnaim** [comment]
Yes I am seeing this too, glad its not just me!

**Comment by Rem0o** [comment]
Is this after a wake from sleep?

**Comment by garethsnaim** [comment]
Hi, not immediately no. I opened it today to adjust the fans whilst playing red dead 2. It did not affect anything game wise but once I quit the game the error was there, when I clicked ok it immediately came back and so on until I quit the app. Earlier in the day I had opened it because I am trying to ease how the fans ramp up, made a few tweaks forgot to close it, later in the day the error was there, and again clicking ok just resulted in it popping up again.

Happy to take logs or what ever tomorrow if it does it again.

**Comment by Rem0o** [comment]
It should pop the first time you open the window after a sleep.  At least, that's the issue I've identified.

**Comment by garethsnaim** [comment]
Hum, thats not my experience, but equally I have not tried opening the app straight after sleep? This only occurred on the very recent update FYI.

Also perhaps unrelated as its been a recurring thing, if I go into another account on my pc then log back into my main one, the main screen for fan control is open, even though it wasn't before.

**Comment by vitduck** [comment]
@Rem0o 

You are right regarding the wake from sleep. 

I've tested again, and the issue does happen the first time Fan Control is opened after waking from sleep.

**Comment by garethsnaim** [comment]
Thats not the behaviour here. After sleep if I open the app its fine. If I close the window then open it again, thats when I get the error.

**Comment by Spuner** [comment]
There's a problem. And most likely it's because the "Check for update at startup" option is enabled in the settings. After the PC comes out of sleep or starts the OS, Fan Control tries to access the Internet to check for updates, but since the PC does not immediately get access to the Internet (the connection is received after ~5-7 seconds) - hence this error.  The solution to this problem is to let the user manually set the time (in seconds) before the update check starts.

And as a temporary solution to this problem - disable "Check for update at startup" in the settings.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V164

**Comment by ClimberMel** [comment]
Same here.  Sent from my Galaxy
-------- Original message --------From: lowfuel ***@***.***> Date: 2023-07-24  6:15 a.m.  (GMT-08:00) To: "Rem0o/FanControl.Releases" ***@***.***> Cc: ClimberMel ***@***.***>, Comment ***@***.***> Subject: Re: [Rem0o/FanControl.Releases] An unexpected error has occurred.  (Issue #1924) 
I no longer get the error with v164, but FYI I now get a dialog box saying "Fan control is refreshing after waking up from sleep", which stays up indefinitely even though things seem to be working(?). It goes away if I click cancel and things are working fine otherwise.
