### ISSUE TITLE
problem with switching configurations

### ISSUE THREAD

**Issue by deartonym** [Rem0o/FanControl.Releases#200]
I found this issue on my end from time to time. 

For certain updates, including current release, switching configurations does not work properly with fan speed control curves. Sometimes the correct curves get activated, but for most times, the wrong curve will be loaded, no matter how you save your configuration.

Any idea how to solve this question? I notice that for some releases this issue does not occur.

**Comment by BB-66** [comment]
I have been having the same issues for the past 4 versions, basically Load Configuration doesn't work at all. If I close to tray, it asks to save the configuration, clicking on "no" will finally load the configuration selected.

This is quite irritating, happened before and it was fixed in a subsequent release then for the past 3-4 versions it seems to be here to stay.

**Comment by DJN0** [comment]
I'm having the same issue. I do something similar to @BB-66 , but I found that if you try to load another config after loading the config you actually want to use, it will prompt you to save the current config, to which you can hit "no", and at that point the program will load the correct config. It's a little more convenient if you don't want to close to tray.

**Comment by BB-66** [comment]
v77 fixed this for me at least. Thank you!

**Comment by DJN0** [comment]
It's fixed for me too.

**Comment by Rem0o** [comment]
Yup, got it sorted out. Closing.

**Comment by deartonym** [comment]
> Yup, got it sorted out. Closing.

Thanks for the fix! it works perfectly right now!
