### ISSUE TITLE
Reset Nvidia 0% hardware curve

### ISSUE THREAD

**Issue by Nildran** [Rem0o/FanControl.Releases#2101]
**Describe the bug**
I own an Nvidia 3080 Founder Edition. By default, without Fan Control, the graphics card automatically shuts down its two fans below a certain temperature.

I wanted to test the control of my graphics card by activating the "Nvidia 0% hardware curve override" option. Once activated, I was able to fully control my GPU fans from 0% to 100%.

After rebooting my PC, I noticed two problems:

- When Fan Control is turned off, the graphics card fans no longer stop. They are now at least 1000 rpm.
- With Fan Control, if I try to set the GPU fans to 0%, they don't go below 30%.

How can I reset my GPU default hardware curve withthe default 0% mode?

**Is there a log.txt file next to FanControl.exe with recent date entries?**
I couldn't find a log file in my FanControl folder.

**Relevant hardware specs and setup**
- GPU : Nvidia 3080 FE
- CPU : Ryzen 7 5800X
- Motherboard : X570S Aorus Pro AX
- OS : Windows 11 22H2 (22621.2428)
- GPU driver : GeForce Game Ready 545.84
- FanControl : 172

**Comment by Rem0o** [comment]
Nvidia 0% hardware curve override does actually "nothing".  Basically, only your card by itself can decide to go 0RPM. FanControl can't force it to.  Anything below 30% results in 30% from a third party like fan control.  What the option does is: when a configured fan curve hits 0%, FanControl is disabled for your GPU, so that it <i>may</i> sets itself to 0rpm if it allows itself to do so.

Each GPU has internal conditions for 0rpm to happen. If said conditions (which can be a mix of current power draw, temp, power profile and load) are not respected, the card won't go 0 RPM.
