### ISSUE TITLE
Feature Request: Curves based on CPU/GPU package power

### ISSUE THREAD

**Issue by threetwenty6ix** [Rem0o/FanControl.Releases#2129]
It would be nice to have a CPU Package Power / GPU Board Power sensors reading and ability to make a fan curve based on those readings instead of just temperature.

Basically would allow to tune fans based on total amount of waste heat instead of temperatures, which makes sense especially for certain CPUs with higher heat density where high temperature doesn't always mean a lot of waste heat.

**Comment by DfrostX** [comment]
See here https://github.com/Rem0o/FanControl.Releases/issues/1790#issuecomment-1557438024

**Comment by threetwenty6ix** [comment]
> See here [#1790 (comment)](https://github.com/Rem0o/FanControl.Releases/issues/1790#issuecomment-1557438024)

Thank you. Bit of shame, still think it would be a neat feature. My CPU can go 80+C while consuming less than 100W but it also can go 80+C while consuming more than that. Hence i would like to have different fan speeds in these two cases. 

With GPUs, the correlation between power and temperature is usually pretty straight, but i still wouldn't mind an ability to control case fans based on GPU power alone.

**Comment by Rem0o** [comment]
Closing.

**Comment by emansom** [comment]
Would also appreciate the PPT/TDC/EDC sensors to be exposed in the UI. 

Got a SFF build with side panels that don't let air pass through that well, only at around 70% PWM the static pressure is sufficient to not let the case heat soak.

The reason as to why I cannot rely on temperature sensors is because I don't run my games at full tilt and/or my 9070 XT is lieing to me.

Old (ten-ish) games at 1080p Medium/High/Very High settings with 90 FPS frame caps.

9070 XT reports it is only reaching 39°C on the hotspot, 34°C package. Thus the fans never kick in, and the heatsoak starts.
GPU+CPU Power usage around 70W+50W, case warm on touch after about a hour of heatsoaking. 

Relying on PPT instead (or better; both temp and PPT somehow?) would allow me to define a curve that more closely follows its real thermal output.
