### ISSUE TITLE
Small issues (popup, two instances, task scheduler)

### ISSUE THREAD

**Issue by ghost** [Rem0o/FanControl.Releases#213]
Great program, thank you very much!
A few small issues i ran into:
1. The donation popup appears every thime i restart my pc, even though i did tick the box (and already donated).
2. When i click on FanControl in my start menu and FanControl is already running, it tries to open a second instance and fails. This leads to the "Close the program" popup from windows.
3. I am running my startup programs with Task Scheduler and a batch file. FanControl is the only only program thath needs a "cd +path" before "START FanControl.exe". Otherwise it is not started.
FanControl islocated in "Program Files (x86),

**Comment by Rem0o** [comment]
FanControl has built-in task scheduler option when you tick the "Start with Windows" option. That might conflict with what you want to do.

the "cd Path" is required so that the current application folder is the one FanControl is in, so that it can find its files next to it.

Try the following: Use the built-in Start with Windows option.  It should start by itself properly, remember the last settings, including the donation checkbox.

**Comment by garrisbibop** [comment]
Thanks for your answer. Unfortunately the same things (i.e. popup, second instance) happen with when i tick the "Start with Windows" box in FanControl.
