### ISSUE TITLE
can not detect any controls

### ISSUE THREAD

**Issue by Wei-Wu233** [Rem0o/FanControl.Releases#2143]
Can not detect any controls with MSI B550M 
I also uninstall the MSI Center,but the issus is still there.
![捕获](https://github.com/Rem0o/FanControl.Releases/assets/66171370/589369dd-702d-4dde-979c-bc708cfac30c)

**Comment by Wei-Wu233** [comment]
Problem solved with setting fans in pwm in Bios

**Comment by burkm489** [comment]
I have several Asus Rog Strix B550-E mainboards for family members featuring the latest UEFI version published by Asus, which worked without visible problems with the latest FanControl Version (up to Version 173). This has changed completely with yesterdays (latest) version 174 as most sensors, even after re-installing version 173, no longer seem to be detected. 
Of those previously 41 detected and listed sensors only 16 have been re-detected now with the new version and are now been shown in a long list of "errors". Re-installing the latest NET 7 version did not include the old hardware library it seems, I removed and reinstalled FanControl Version 173 with the most current config file because of this, but this no longer works either (which it did up to yesterdays update)
.
Most of the displayed top line of my (re-installed) FanControl UI is now empty. Looks like the author has rewritten the detection library used and introduced some errors with it.

**Comment by Rem0o** [comment]
@burkm489  if you reinstalled V173 from scratch and your problem persists, then it has nothing to do with the V174 changes.  Also please if you have a specific issue, do not just copy paste the same text in multiple issues, it makes it unnecessarily harder to manage these original issues and yours.

**Comment by burkm489** [comment]
Hi there,

 

My original Fan Control folder disappeared completely during the update to 174. 

Version 173 functioned up to that moment just fine and without any problems. All 41 sensors where visible und functioned the way they were supposed to.

After that the original FanControl folder seem to have disappeared completely from all of my drives after an error message flashed for a second (?) during the proposed update.

When trying to reinstall version 173 and/or installing version 174 I get the error messages now, that many of the original 41 sensors are missing (only 16 are now visible) and some of those 16 additionally carry the temperature value of “0”.

The problem appeared solely during that update.

 

I have been able to recover the original configuration files, which I did save in irregular intervals. The last one had been saved a few weeks before the update, but those missing sensors (41 => 16) did not reappear after importing the original configuration file.

Especially the CPU sensor seem to have disappeared (and readable) although still visible in the UEFI.

Thus a lot of those sensors seemed to be “lost” by now within FanControl no matter, what version I try to install and I don’t seem to get them back.

 

 

Von: Rem0o ***@***.*** 
Gesendet: Donnerstag, 23. November 2023 16:13
An: Rem0o/FanControl.Releases
Cc: burkm489; Mention
Betreff: Re: [Rem0o/FanControl.Releases] can not detect any controls (Issue #2143)

 

@burkm489 <https://github.com/burkm489>  if you reinstalled V173 from scratch and your problem persists, then it has nothing to do with the V174 changes. Also please if you have a specific issue, do not just copy paste the same text in multiple issues, it makes it unnecessarily harder to manage these original issues and yours.
