### ISSUE TITLE
Crashing on startup since last update

### ISSUE THREAD

**Issue by mr2cam** [Rem0o/FanControl.Releases#217]
Been getting a crash on startup since the latest update, I do not have anything in task scheduler that starts up, just have the box checked to start with windows on FC.

**Comment by Rem0o** [comment]
un the Updater.exe and delete the task in the task scheduler before starting back fancontrol.

**Comment by martinsstuff** [comment]
FYI The update still doesn't seem to have fixed it. The task is still created with the forced stop after 5 minutes. I just updated to the latest version and dis/enabled the auto start and checked the created task.

**Comment by Rem0o** [comment]
@martinsstuff I did change the task, the action now is a fire and forget of the application, so the task only runs for a second.

**Comment by akelsall1** [comment]
Have been trying out (using) FanControl constantly for around two months now.
With not being able to see the source, I'm pretty concerned there aren't any unit tests around this.
You've built a great piece of software, but one that controls a **critical** part of the system. The crashing is bad, but the lack of any alert or information when it crashes could be catastrophic for your users.
It has now crashed **while** playing games twice for me, disappeared without a trace and left my fans at a lower speed than they should have been at causing temps to be alarmingly high.
Secondly, as a warning to everyone using this software, when your computer is shutting down and windows is closing the applications, that also means FanControl is closed. As happened to me, if for some reason your CPU is working hard at this point, without FanControl running, trying to restart or shutdown, the CPU temp goes crazy. I know this because when it rebooted, the bios errored with an overheat warning. The first time I have ever seen one.
Beware using software fan control. I'm going back to bios after that experience and the apparent lack of unit tests around this hidden code.
Sorry, and thank you for your work.

**Comment by Rem0o** [comment]
@akelsall1 it’s not a crash, it’s the task that was stopping the application. The program is unit tested for the main part, but you can’t cover IO stuff or state like everything that relies on Windows stuff, here the task scheduler. I did messed up the task. The goal was for it to not be overridden everytime the programme starts, but that caused some nasty sode effects I did not see coming and I’m sorry for the inconvenience.

**Comment by Rem0o** [comment]
V77 overrides the task for good.
