### ISSUE TITLE
Cannot update to v76/ Option to disable auto update check

### ISSUE THREAD

**Issue by assist726** [Rem0o/FanControl.Releases#218]
I'm currently on v74 and every time when launching I get an update notice for v76, however it never downloads successfully and it appears that in releases we are only at v74?

1. Should the releases be update to v76?
2. Could you include an option to disable auto update checking?

**Comment by Rem0o** [comment]
What do you mean "not download successfully"?

**Comment by Yur0K** [comment]
I'm facing the same issue. After tapping Update button - nothing happens

**Comment by Rem0o** [comment]
From which version? Just downloaded V74 and the update works.

**Comment by sctanf** [comment]
I used v74, skipped the update to v75. v76 installed without issue.

**Comment by Yur0K** [comment]
> From which version? Just downloaded V74 and the update works.

From 75.
Updated manually with Updater.exe to 76

**Comment by assist726** [comment]
> What do you mean "not download successfully"?

After clicking the download button it starts downloading but hangs indefinitely.

I can confirm it's not a network issue and previously my updates between v70-> v74 worked fine.

**Comment by tormento** [comment]
Same here.

**Comment by Rem0o** [comment]
> Could you please release a compiled version of latest?

The updater is downloaded from https://github.com/Rem0o/FanControl.Releases/blob/master/Updater.exe.
FanControl itself is right here https://github.com/Rem0o/FanControl.Releases/blob/master/FanControl.zip

**Comment by assist726** [comment]
I ended up manually updating to v76 from downloading the new complied release. Updater never ended up working.

**Comment by tormento** [comment]
I keep on getting same error since that same version.

Apart from manually applying, I have no idea how to fix it.

18/05/2021 22:55:18: Unhandled exception in FanControl v1.0.0.0
18/05/2021 22:55:18: System.Net.Http.HttpRequestException: Si è verificato un errore durante l'invio della richiesta. ---> System.Net.WebException: Richiesta annullata: Impossibile creare un canale sicuro SSL/TLS..
   in System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   in System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in FanControl.Domain.UpdaterService.<UpdateVersion>d__10.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in FanControl.Domain.UpdaterService.<<CheckForUpdate>b__7_0>d.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in FanControl.Domain.DialogService.<>c__DisplayClass7_0.<<ProgressDialog>b__0>d.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
18/05/2021 22:55:18: System.Net.WebException: Richiesta annullata: Impossibile creare un canale sicuro SSL/TLS..
   in System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   in System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
