### ISSUE TITLE
Feature Request: Enable more sensor types

### ISSUE THREAD

**Issue by zeroflow** [Rem0o/FanControl.Releases#2205]
Hi Rem0o!

I'm really like your software, but I'm currently looking at how to implement a usecase I want to use:
Different behavior based on PC usage, e.g. fans turning off when idle, but always on (20%) when gaming.
I've had some annoyances with fans toggling on/off all the time especially with less taxing games. I can change profiles where the fan curve is always active, but where's the fun in that.

The idea i'm having is to support additional sensor types to be read - for example power or utilization.

My concept would be as following:

* Settings -> Sensors -> Edit sources... : Add "Types of sensors" to LibreHardwareMonitor settings
* Types of Sensors: Temperature (always on), Powers (default off), Load (default off)

Since these types already exist inside LHM, I hope this is not too much effort.

This would allow me to have different behavior when gaming. The following is an example of what I want to achieve by creating file sensors as placeholders.
In this example, the power curve goes to 20% as soon as CPU+GPU Power is above 40W. That way I can keep the fans from turning completely off when the system is under load.

![image](https://github.com/Rem0o/FanControl.Releases/assets/1294885/633a5fb7-0171-4253-8ae5-c5aa98b4c965)

**Comment by Rem0o** [comment]
You could replace probably all of that with a simple Trigger in your Mix instead of the "Power" curve.   Give it a shot.

**Comment by zeroflow** [comment]
Yeah, a Trigger would do the job of the power curve as currently implemented.

My feature request is regarding adding the sensor inputs for the power values.

For this mockup, I just manually created files having some values. But I would have to write a piece of software that reads LHM/HWInfo and then writes that info into the file. 
I'm asking for this feature, as the sensor values should already be present in LHM but are not used since FanControl only reads in temperatures. Optionally, I was thinking about changing the [HWInfo plugin](https://github.com/Rem0o/FanControl.HWInfo/blob/master/HWInfoPlugin.cs#L63C21-L71C22) to also report power values as temperatures, but a direct change request may yield a more beautiful solution.

**Comment by Rem0o** [comment]
> My feature request is regarding adding the sensor inputs for the power values.

My question is more, why not use what's already existing  like a simple trigger instead of this power setup.   

Your problem is the following:

> I've had some annoyances with fans toggling on/off all the time especially with less taxing games. I can change profiles where the fan curve is always active, but where's the fun in that.

You could for EG sum the temp of CPU + GPU, and trigger idle only when the sum is the usual temp for both idle, let say 30 (CPU) + 40 (GPU) = 70 or something like that, will depends on your component. You could then even time average it for like 15 seconds or more to get a good approximation of a true idle state of your system.  This way you will only stop your fans if your system is truly idle.

![image](https://github.com/Rem0o/FanControl.Releases/assets/14118956/a6cb8622-3816-465a-b7ab-a4f9f20a7a18)

I'm asking specifically because I want to know if your use case is covered with existing features, or is it just you're thinking of the problem a different way and want to solve it using a different/new method for the sake of it.

**Comment by zeroflow** [comment]
Ah yeah, now I get what you meant in the first comment.

I will try, thanks for taking your time with those answers.

**Comment by zeroflow** [comment]
Thank you for your ideas. The Sum combined with triggers allowed me to reach the goal without having to resort to external means.
