### ISSUE TITLE
Is it normal for the app control window to look very laggy when being moved around the desktop?

### ISSUE THREAD

**Issue by Globespy** [Rem0o/FanControl.Releases#2212]
**Describe the bug**
Window contents are laggy when moved around the desktop. No such problem with regular windows explorer windows.
Not function breaking, just wondered if it's normal or if there's anything I can do to fix?
[Link it here]

**Relevant hardware specs and setup**
AMD 5800X3D
Gigabyte Aorus X570 Master (rev 1.2)
Zotac RTX 4090 Amp Airo Extreme - using older driver 528.49 Studio as it's the most stable with lots of problems with the new drivers.
32GB G.Skill Trident Z Neo 3600Mhz
EVGA G6 1000W PSU
EKWB 360 Elite AIO

Latest version Fan control
Win 11 - build 22631.2861

**Comment by Rem0o** [comment]
Not normal, but since it seems like an isolated issue you are experiencing, there is most likely something wrong/different on your end.  Do you have a high refresh rate monitor with gsync? Sometimes you got to set settings in the Nvidia control panel to turn off these features for a specific app and the problem might go away.

**Comment by Globespy** [comment]
Thanks! I will try this out, although not sure I can do that for just the Fan Control app? My monitor uses GSync, but don't most monitors use some form of adaptive sync technologies these days (Freesync etc)?

**Comment by Globespy** [comment]
Issue is resolved, was caused by another program Process Lasso.
