### ISSUE TITLE
ASUS GTX 1060 DUAL OC 6 GB 2nd FAN always on.

### ISSUE THREAD

**Issue by Feinbeerg** [Rem0o/FanControl.Releases#2233]
FanControl is able to only control one of the fans on the GPU , the second fan always runs and its speed cannot be changed.

I have had this with MSI Afterburner and this GPU aswell, only program that managed to control it was GPU Tweak II.

The Reported speed in FanControl is 0 RPM for the one fan, the other fan does its own thing.

**Comment by Fr0stX76** [comment]
I'm fairly sure the second fan is on a seperate Asus controller instead of on the Nvidia one. This is why no tool outside Asus one is able to control it. See [here](https://forums.tomshardware.com/threads/asus-dual-1060-6gb-only-one-fan-keeps-spinning-on-idle-for-no-reason.3712917/).

Sadly unless Asus decide to share some code (very unlikely), it is what it is...
