### ISSUE TITLE
FanControl does not open up/appear in tray in Windows 11...

### ISSUE THREAD

**Issue by Restore4u** [Rem0o/FanControl.Releases#2246]
Somehow, FanControl's stopped appearing in my system tray. I cannot figure out whether it's running or not. It doesn't say anything in Task Manager or start up apps either... When I go to the FanControl folder and open the exe, nothing happens...

I basically cannot access the app any longer, for some reason.

I've used FanControl for about 1 year now without any issues, but now, it just doesn't work anymore...

There was no logfile next to the .exe in the folder either...

I've got no AV/firewall on or something like that... So yeah, how do I fix this?

**Comment by Rem0o** [comment]
Does in run in task manager? Under what user?

**Comment by NoClueLemmeTry** [comment]
Do you by any chance have Corsair's iCue software installed?
I've just had the very same problem, on a Windows 11 / 10 dual-boot system. It didn't work on either OS. It worked yesterday.
I installed Corsair iCue on both yesterday. I just uninstalled it on both systems, and would you believe it, Fan Control is working again.

**Comment by FLAMEKKi** [comment]
I am having same issues. Cant see it in Task Manager, running as admin wont do anything. Dont have Crosair software on my system.

**Comment by Rem0o** [comment]
Any logs?

**Comment by dazzlemon** [comment]
It stopped working for me too, but I changed mobo and ram, and also windows updated itself

**Comment by dazzlemon** [comment]
fyi I uninstalled these updates, and it works now:
- kb5034122
- kb5034441
- k,b5033918

**Comment by FLAMEKKi** [comment]
I just downloaded new version nad it works now.

**Comment by bsh-hub** [comment]
I had this same issue. For me it seems that the update process failed for some reason and at least partially caused this. Now I am running the latest version (v179) and everything works as before. I was able to get the update process working by renaming the Newtonsoft.Json.dll to Newtonsoft.Json.dll.old before running the update (the system allowed the rename even though the Updater said the file was used by another process).

`C:\apps\utils\fancontrol>Updater.exe
Fan Control Updater

Downloading Fan Control v179...
Extracting archive...
Extract failed: System.IO.IOException: The process cannot access the file 'C:\apps\utils\fancontrol\Newtonsoft.Json.dll' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at Updater.Program.Extract(Stream zipStream, String extractDirectoryPath)
Restarting Fan Control...

---- renamed the Newtonsoft.Json.dll before trying again ----

C:\apps\utils\fancontrol>Updater.exe
Fan Control Updater

Downloading Fan Control v179...
Extracting archive...
Validating checksums...
Success! Fan Control V179 will start...
`

**Comment by Rem0o** [comment]
@bsh-hub  Try deleting the updater.  For a while the updater was using the same version of Newtonsoft as FanControl, which caused the conflict.

**Comment by medoro** [comment]
same here: opens in task manager doesn't show any windows or icon.

Ah, the great open source tools!

Fantastic when they work properly.
