### ISSUE TITLE
Default fan speeds stuck at 100%

### ISSUE THREAD

**Issue by not1336** [Rem0o/FanControl.Releases#2295]
**Describe the bug**
When I was initially setting up my fan curves, I experienced a BSOD. Now during startup or when the application is disabled the fans I had initially adjusted run at 100%. They are set appropriately in the bios, and adjusting them there doesn't slow them down anymore.

My CPU pump, which I didn't make any curve adjustments to before the BSOD is still running according to the bios settings, only my case fans and radiator fans were affected.

**Relevant hardware specs and setup**
mobo: b650 x gaming ax v2
cpu: 7800X3D
case: Lian Li 216

You can see below, "CASE FAN" and "RADIATOR FAN" are the ones affected.

![FanSettings](https://github.com/Rem0o/FanControl.Releases/assets/47046052/88c29bc1-cd9a-420c-979a-7014857e195d)

**Comment by not1336** [comment]
Update: reflashing my bios to the same version (F4A to F4A) again resolved this.

**Comment by not1336** [comment]
It happened again. BSOD and fans operate at 100% outside of the app.

**Comment by vitduck** [comment]
@not1336 

Unfortunately 100% fan speed is just a Gigabyte thing. 

I'd recommend avoiding GB if you plan to use 3rd party fan control. 
GB is the only vendor who use proprietary IO chip. 
The issue is likely with the backend and not Fan Control itself.  

https://www.reddit.com/r/gigabyte/comments/144w41f/issues_with_3rd_party_fan_control_softwares/

**Comment by not1336** [comment]
oddly enough the BSOD was related to a USB device (hyperx microphone), once removed I haven't experienced this issue.
