### ISSUE TITLE
KFA2 RTX4070 - Calibration failed partial

### ISSUE THREAD

**Issue by Braindea7** [Rem0o/FanControl.Releases#2380]
Hey,
I work with Version 184 and want to calibrate my fans. 
The Problem only accures with the RTX4070 outer Fans. It's a 3 Fan GPU which are seperated in 1 inner and 2 outer fans. The calibration for the inner fan run through without any issue, but I'am not able to calibrate the outer ones.

If I start the calibration for the outer GPU fans they speed up to 100%, wait to the max RPM and after that the calibration window close by itself and the calibration stops with the fan at 0% and it stays with "No Calibration".

I'am using the NvAPIWrapper and I hadn't any issues with that until today.

**Comment by Rem0o** [comment]
Curious, while it tries to figure out the max value, what kind of oscillation in the RPM value are you observing? Does it ever stabilize ?

**Comment by Braindea7** [comment]
It seems to stabilize at ~3,4/3,5k and as soon as it is stable the calibration get cancelled.

**Comment by Rem0o** [comment]
Yeah that's were it fails.  The calibration process will try to see a stable value within +- 32 RPM over 3 seconds.  It timeouts after 20 seconds. In that case it should take whatever value and move on still with the process.  Will be fixed in the next release. In the meantime you can always do a quick manual calibration with the calibration dialog when you click on the "no calibration" label. You can do 4-6 points and it will be plenty.

**Comment by Braindea7** [comment]
Nice :)
Yeah that's what I meanwhile did already.

Thanks for your quick response.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V185
