### ISSUE TITLE
FEATURE REQUEST - show the corresponding percentage value in RPM mode curves

### ISSUE THREAD

**Issue by godzinilla** [Rem0o/FanControl.Releases#2466]
Hello!

I am currently running the RPM mode for my Controls and Curves.

The Control card shows the RPM value corresponded to the PWM value of the control.

If you use the Curve for this Control and the Curve is switched to RPM instead of PWM - you are operating on the RPM values only without knowing the percentage value for given RPM.

Currently there is no option to seamlessly switch between RPM and PWM in the given Curve (you need to create individual ones).

**REQUEST**: Would be great to have a view in the Control card what PWM percentage corresponds the given RPM value.

Thank you!

**Comment by ionGL** [comment]
RPM mode **curves** can't show %, because it's impossible for a RPM **curve** to know what % represents an RPM. The RPM curve is not assigned to a control yet. The calibrated **control** cards, when assigned to an RPM curve, will translate the requested RPM to a %, based on that control's fan calibration.
On top of that, an RPM curve can be assigned to multiple controls. Those controls will set different % values for their fans, based on the individual calibration.
