### ISSUE TITLE
Updating to V188 has broken GPU temperature readings

### ISSUE THREAD

**Issue by secomak** [Rem0o/FanControl.Releases#2482]
After updating to V188, Fan Control now reckons my 7800 XT core temp is 125C, this is definitely not accurate as you can see with AMD Adrenalin next to it lol. The GPU memory temp is also pinned at 192C. However, GPU Hotspot temperature appears to be working as intended still.

![image](https://github.com/Rem0o/FanControl.Releases/assets/134750814/09549ef5-8948-43e2-babb-96257ba660d4)
![image](https://github.com/Rem0o/FanControl.Releases/assets/134750814/8cfe53fd-a203-460d-89b5-710e02c39b67)

**Comment by Rem0o** [comment]
I would recommend going with https://github.com/Rem0o/FanControl.ADLX for Navi3 gpus.

Disable the GPU section in sensor settings if you do so.

**Comment by secomak** [comment]
Thank you, I have just done exactly that and the GPU temps are behaving normally with this :)

I initially thought this plugin was just if you wanted to control the GPU fan speed through Fan Control? As I was fine with Adrenalin handling this, but I take it the plugin is now recommended for just fetching the temperatures of the GPU too?

**Comment by Coolio47** [comment]
Rem0o:  I have recently downloaded and utilized your FanControl software.  Huzzah.

My problem:  GPU:  AMD Radeon Sapphire HD 6900 video card, circa 2007.  Swapped it out recently for a new(er)(2011) graphics card, that died a few days ago.  Swapped this Sapphire card back.  The GPU sensor was recognized by FanControl, I set up the Speeds and Curves.  Worked like a charm.  Had been having screen tear and screen artifact issues for awhile (which is why I swapped out for a new(er) graphics card).

Started with FanControl V.187, saved configuration.  Your software recognized the GPU, CPU and both intake and outtake fans.  Set up the Curves, still working.

Then yesterday, got the message that a new Version was released (v.188).  Went through the automatic update process.  No problems.  Then, while playing City of Heroes, got some screen tear.  Finished the game, rebooted (seems to fix screen tear, if only temporarily).  After reboot, opened up FanControl, and the GPU fan control and sensor were missing.

Multiple reboots, reset the CMOS, removed and reinstalled memory, took the video card out and put it back in, more reboots.  Checked power connections (power supply is 850W), power supply, cables.  No dice.

Windows 10 still recognizes that there is an AMD Sapphire 6900 HD video card installed and functioning, and I can see to type this issue.

Per these boards, I downloaded and installed the ADLX for AMD video cards plugin (not sure why it was working without that, in V.187).  And not sure why I now need that plugin for v.188 (still not working).

FanControl recognizes that there is something there called Fan#1, but it is greyed out.  Under Curves, there is no sensor for the AMD Radeon 6900 video card (but there was before the V.188 update).  FanControl recognizes my AMD Ryzen 5 1600 CPU and both external HDs, the intake and exhaust fans (Fans #5 and #6), but no longer recognizes the sensor/control for my video card.

This is a wonderful piece of software and I would like to get it working again.

Thanks for your effort and help.

**Comment by Rem0o** [comment]
@secomak  The plugin is just a way to develop something on the side as optional/opt-in, but it will join the main software (built-in) soon enough.

**Comment by Coolio47** [comment]
UPDATE:  I deleted V187 and V188, from my system.  Unzipped V187, ran it.  V187 recognized by GPU, without the ADLX plugin.

Configured fans/fan curves, and all is back to what it was before the V188 update of 30 Apr 2024.  Will hold off on updating to V188 (though I have downloaded and saved the .zip for V188, for the future), until either something is definitive about recognizing older video cards or whatever "bug"/issue in V188 that is not recognizing video card, is fixed.

Thanks for your time and a great piece of software.

**Comment by pkuiters** [comment]
Hi, I have the same problem on an Navi2 GPU, e.g. the 6950XT. Using the plugin as suggested, solves the problem.
Thanks!

**Comment by ClimberMel** [comment]
What is the best way to revert back to older version?  I get a number of errors with v188 and my GPU is no longer recognized for fan or temp.  (Radeon HD-6790)

**Comment by Rem0o** [comment]
See V189 for the sensors with broken values.

**Comment by UnknownBlader** [comment]
I am using ADLX plugin and gpu sensor seem to be broken
![Screenshot_104](https://github.com/Rem0o/FanControl.Releases/assets/71110861/093410d7-1fcf-4e64-9b4f-67224104c35a)

**Comment by UnknownBlader** [comment]
updated 
![Screenshot (6)](https://github.com/Rem0o/FanControl.Releases/assets/71110861/a824f6fb-6989-4b15-9ef8-33d0b08d930e)

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V190
