### ISSUE TITLE
Improvement: sync tray icon color with Windows theme

### ISSUE THREAD

**Issue by JenChiaik** [Rem0o/FanControl.Releases#2562]
In Windows 11, **Dark / Light** modes can be seperately applied to **Windows GUI** and **app GUI**.
But when I enable _sync tray icon color with Windows theme_, it actually sync with App GUI's color theme rather than Windows.
That is, if my task bar is in DARK mode and app GUI is in LIGHT mode, the tray icon is DARK in the DARK taskbar.
Is it because Windows provides no api to access the Window GUI mode?

**Comment by LRJuuu** [comment]
+1 
Many times, when the computer wakes up after turning on or sleeping, the color of the taskbar icon does not synchronize with the window theme. But when you open FanControl, the main interface of the software follows the window theme normally. At this time, you can reopen "sync theme with windows" in the settings, and the taskbar icon will return to normal.

**Comment by LRJuuu** [comment]
It has been a month since you raised this issue and the bug has not been fixed. According to my observation, this problem actually occurs because when the system switches between dark and light modes, although fancontrol also synchronizes the ui at the same time, it does not save this setting. When you open When fancontrol is closed again, you will be prompted whether to save the settings, so in my opinion, the setting for switching between dark and light interface colors can be separated into a configuration file and then enable automatic saving, which will solve the problem. It's a pity that I can't program. I hope programmers in the community can solve it (via Google Translate)

**Comment by JenChiaik** [comment]
This issue was fixed after V196 release.  : )
