### ISSUE TITLE
Suggestion: Relative Offset 

### ISSUE THREAD

**Issue by photon1503** [Rem0o/FanControl.Releases#26]
Hi, currently the Offset works with a fixed percentage. It would be good to have an option to also have a relative offset.

i.e. Currently we have
Input = 70%, Offset = -20%, Result = 50%

Suggestion:
Input = 70%, Relative Offset = -20%, Result = 56%

**Comment by cmeeren** [comment]
I would like this, too. For some reason, my three GPU fans (MSI RTX 3080 Gaming X Trio) are divided into two fan controls (2 + 1), and the one with 2 fans has lower RPM for any given fan percent.

Currently, I have two separate curves for these controls, and I have manually checked various fan percents vs. RPMs to adjust the two curves so that the RPM matches approximately for any given temperature. If I want to adjust the curve, I have to do this all over again.

A relative offset would solve this in my case, since I could have only one curve and just apply a relative offset to one of the fans.
