### ISSUE TITLE
V196 Temperature Sensor no longer displayed in Taskbar after reboot

### ISSUE THREAD

**Issue by tall1on** [Rem0o/FanControl.Releases#2619]
Sometimes my AMD CPU temperature sensor disappears from the taskbar when I start my PC. One of the last versions seems to have fixed the problem for me, but with the current version (V196) it's back.

Sensor is gone:
<img width="220" alt="lHw3j39aOm" src="https://github.com/user-attachments/assets/9bb711b7-5b7d-45b2-bf85-9166f07108b9">

Sensor is suddenly missing from settings:
<img width="449" alt="FanControl_2CFVUQKbiA" src="https://github.com/user-attachments/assets/3558f21f-75da-4fd2-9143-91f91991bc7a">

The following sensors are affected by the bug:
<img width="256" alt="5sr1EVVaxo (1)" src="https://github.com/user-attachments/assets/3c510145-4c0e-4bce-974b-303a105e08d9">

**Comment by Rem0o** [comment]
I noticed the program doesn't warn the user if there are missing sensors for tray icons when the configuration is restored.  I suspect you are experiencing an error but it is not logged/notified. I will patch that hole in the restore process.  
Otherwise, it's hard to say why the sensors fail to be seen by the program. 

What kind of delay do you have for start with user logon in the settings?

**Comment by tall1on** [comment]
Screenshot of all my settings:
<img width="1916" alt="FanControl_XSNf8I4R8M" src="https://github.com/user-attachments/assets/07a8fd2b-231d-46e3-be2f-1ec765a6c62d">

**Comment by tall1on** [comment]
Today it happened again immediately. Seems to be really more frequent with V196, before it was only every few days.

**Comment by tall1on** [comment]
I just added the temperature sensor back to the taskbar and everything had worked, now after a few minutes the GPU temperature sensor has disappeared in the middle of operation.
