### ISSUE TITLE
v84 seems to have broken Storage sensors

### ISSUE THREAD

**Issue by kuraikaze** [Rem0o/FanControl.Releases#275]
### All storage sensors now reading at 0°C

Fan Control V84 on Windows 10 Pro 21H1

Storage sensors were (mostly) working fine for me with v83 and prior.
Tried "Refresh sensors detection" and checked with "Disable storage sensors" option off and on, in case it was a simple Boolean mishap.

Note:
I say "mostly" working earlier because although SATA drives always worked fine there were a couple of oddities with Samsung NVME drives. 

1. 960 EVO - Showed 3 values despite only having 2 sensors on the hardware. The 1st and 2nd entries were always duplicates of each other.
2. 980 PRO - Still fails to display any values (in v83 and prior), despite support being added to LibreHardwareMonitor back on Feb 12th 2021 (https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/5e2f395a21179784098b5927ab9ffcc322e9ec7b)

**_Edit: Never mind re 980 PRO - just looked at LibreHardwareMonitor and the last Stable (non Beta) release was 0.8.7 back on Feb 9th.  Oops ;)_**

Saved log from clipboard:
[fancontrol.log](https://github.com/Rem0o/FanControl.Releases/files/6719644/fancontrol.log)

**Comment by carsanwitt** [comment]
Just noticed the same missing sensors, with very similar drives: 980 Pro and 970 EVO Plus on a B550i Aorus Pro AX.

Both drives reported temps correctly since I built my PC 2-3 months ago (3 temps on each, so maybe there was a duplicate issue there but I didn't mind since I used a Max function on them.)

Fan Control was actually really helpful in keeping the M.2 temps in check since I had quite some overheating issues with the default heatsink of the mobo, which were solved with a replacement heatsink and some smart fan curves.

No, I see "0°" on both drives.

**Comment by kuraikaze** [comment]
Hrmmm.
Odd that your 980 Pro showed a value and mine never did.
Motherboard is an Asus TUF Gaming X570-Plus.

**Comment by katnapped** [comment]
Both my SSD's (WD SN850 and ADATA SP550) also failed to show their temperature (shows 0).
My motherboard is ASUS PRIME Z270-A.
Let me know if any more info may help!

**Comment by Rem0o** [comment]
Found the issue, will fix.

**Comment by Rem0o** [comment]
https://github.com/Rem0o/FanControl.Releases/releases/tag/V85
