### ISSUE TITLE
[Feature Request] Round percentages, RPM, temps to the nearest whole number

### ISSUE THREAD

**Issue by dcog989** [Rem0o/FanControl.Releases#2846]
Request to round reported fan percentages + RPM, and sensor temps to the nearest whole number.

Reason - the reported values are approximate and therefore the margin of error is greater than the fraction that is reported. Plus, no one has a practical use for '38.3%' vs '38%', or '44.7C' vs '45C'. 

Therefore, remove the visual clutter by rounding to the nearest whole number for each.

**Comment by Fr0stX76** [comment]
I disagee for temps. That "clutter" is usefull for people with water temp setups, which vary by decimals, not by round numbers.

Fans maybe, but does it really clutter that much?

**Comment by dcog989** [comment]
Does anything really matter that much?

For anyone with an appreciation for good design / UI / UX, yes, it matters that there is pointless clutter / noise that distracts from the information being presented.

What does someone with water do with 0.3C that someone with air doesn't?

**Comment by Fr0stX76** [comment]
Water doesn't vary as fast and has a much compared to air.

On idle my water temp is ~26c, while in gaming, ~around 31c and that, after 30 minutes of ramping up slowly. Being able to use decimals gives much more granular control/smoother curves since I only have 5 degree on my graph's X axis. This is a feature for some, not a clutter.

**Comment by dcog989** [comment]
With those unbelievable temps you wouldn't need to worry about hysteresis.

Either way, it's just the illusion / delusion of fine-tuning 0.1C at a time.

**Comment by Fr0stX76** [comment]
Since you clearly don't understand how water-cooling work, I think you should refrain from commenting on it. Speaking of illusion, it's quite amusing to read this considering your request is 100% driven by an ocd, is purely cosmetic and has no functionnal value.

I'm done here, nothing to add. It's up to Rémi to decide...

**Comment by dcog989** [comment]
Please do not comment again. You've added nothing of value.

**Comment by Rem0o** [comment]
> no one has a practical use for '38.3%' vs '38%', or '44.7C' vs '45C'.

That's an assumption, and a wrong one at that.  

For %: The effective steps for % is 256, so 100 steps isn't enough to represent the range's resolution
For temperatures: Water-cooling setups especially may need that resolution as stated by @Fr0stX76 
For RPMs:  Not real reason here, RPMs could be have no decimal and it would be fine. 

It was whole numbers before, people requested single decimal, this is where we are now.  I feel like single decimal is a good compromise between "clutter" and effective resolution for fine tuning.  I don't feel like adding yet another setting for such a detail is worth it. 

Closing.

**Comment by dcog989** [comment]
I just checked every cooler / AIO that offers a temp display - none of them display fractions. No doubt because they all realise that it's pointless detail and delusional to believe otherwise.

Plus, none of what you've written addresses the nonsense of displaying fractions for RPM / %. Oh, well...

**Comment by Fr0stX76** [comment]
https://owneaster.com/pc-water-cooling-temperature-display/

**Comment by dcog989** [comment]
Awww. How desperate. Now post the vast majority.

**Comment by Rem0o** [comment]
Dude that's enough. Stop with the attitude.  You got answered, now move on.

**Comment by dcog989** [comment]
Answered to *your* satisfaction, maybe.

But, fair enough. Some people get good design. Other people want to see useless information in order to feed a delusion that they're doing something useful.
