### ISSUE TITLE
Auto-detected controllable fans don't show up in controls list

### ISSUE THREAD

**Issue by Chase817** [Rem0o/FanControl.Releases#385]
Repro:

1. Launch assisted setup
2. Make sure that your GPU fans are detected and can be controlled with the sliders
3. Click OK
4. Currently for me, these fans I just controlled with the sliders are nowhere to be found

See the screenshots below. Note that these controls show up in the sync curve list, but don't show up in controls...

![Capture](https://user-images.githubusercontent.com/1311907/141390906-50c2ef89-b41f-458c-9514-74b034b7aca3.PNG)
![Capture2](https://user-images.githubusercontent.com/1311907/141390917-8aad9c0e-644f-4e1f-b895-623904cc8dee.PNG)

**Comment by Rem0o** [comment]
First off, there is a visual bug in the identification dialog, will fix that.

Second, about the missing fans, that mean those fans were hidden, because at some point you ran the assisted setup and the fans couldn't be controlled. You probably reran the setup an other time after you changed something making your fans controllable.  Seems like the assisted setup will need a bit of refinement.

In any case, you can bring back the fans with the checkbox from the hamburger menu "Show hidden cards".

**Comment by Chase817** [comment]
Thanks for the tip, that worked!
