### ISSUE TITLE
[Feature Request] Sensor rename

### ISSUE THREAD

**Issue by TimSirmovics** [Rem0o/FanControl.Releases#417]
It would be nice to define custom names for some sensors, as the default names are often quite long and hide the most important information.

e.g. These GPU sensors from Libre all contain the GPU name at the end:
![image](https://user-images.githubusercontent.com/10243286/144769115-1944e343-53b3-4e2f-aee0-a1cf9b05c5dd.png)

When applied to a curve you can't see the part of the name which seperates the sensors:
![image](https://user-images.githubusercontent.com/10243286/144769151-202345ff-b40f-4b2e-bf0b-7d9ce81d25b5.png)

In this example I would rename them to "1080 Core" and "1070 Core".

**Comment by midcode** [comment]
Another benefit of renaming sensors would be to help remember which temperature sensor is which. It's quite confusing sometimes. 
Additionally on many gigabyte boards many sensor names exist twice in the list because the boards have two fan controller chips.

![image](https://user-images.githubusercontent.com/6597617/153640767-729e9d8b-760b-436f-b5c7-a20ea1ac0d57.png)
as you can see Temperature 1-3 exists twice

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/153666009-940d26ca-6b66-4d23-9121-c6588d9f18ae.png)

It's a fine idea.

**Comment by Rem0o** [comment]
See V105.
