### ISSUE TITLE
Start on Launch doesn't seem to enable plugins

### ISSUE THREAD

**Issue by richraid21** [Rem0o/FanControl.Releases#420]
Hi, first of all, thank you for the great product. 

However, I'm having some trouble getting the HWInfo Plugin to enable itself when the program is auto-launched on Windows boot. 

If I manually launch the program from the directory, the plugin is enabled and my sensors work properly. However, when auto-booted after a restart, the program complains that sensors are missing. I look in the sensor settings and the HWInfo Plugin is not listed (although it is the directory). 

Any ideas?

**Comment by Rem0o** [comment]
At the time FanControl started, HWInfo was not properly initialized.

**Comment by richraid21** [comment]
Could you elaborate on that? I have HWInfo set to start on launch and give Fan Control a 45s delay

**Comment by Rem0o** [comment]
Well that's a guess, as it relies on HWInfo setting up a shared memory first, which FanControl then fetches from.

Any log.txt?

**Comment by Rem0o** [comment]
By the way, since this is a HWInfo plugin issue, you should post this issue on the main repo.
https://github.com/Rem0o/FanControl.HWInfo

Also, code is open source, you can attach to the FanControl process from Visual Studio with the code and you will know what's up.

That plugin has not proven reliable at all, and it is the cause for something like 25% of total issues I receive. I'm thinking seriously of archiving it at this point until somebody PRs something or I have the time/desire to change the implementation.

**Comment by richraid21** [comment]
There doesn't seem to be any logs generated from the event, but if I notice any I will update this. 

Thanks for the help

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/145644869-57ddb440-5199-4609-88ae-16e308736305.png)

**Comment by richraid21** [comment]
I will try again, but I deleted my `log.txt` to get a clean one for you, and restarted but none was generated

**Comment by richraid21** [comment]
> Well that's a guess, as it relies on HWInfo setting up a shared memory first, which FanControl then fetches from.

I changed my startup delay to 2 minutes and I'm not longer getting an error, so it seems like HWInfo takes way more time than I thought to setup shared memory. 

Thanks for the help
