### ISSUE TITLE
Fan drift

### ISSUE THREAD

**Issue by Sylvanas-1977** [Rem0o/FanControl.Releases#465]
As if fan control loses control either all 3 fans drift from what they supose to idle at around 850 rpm up to 1050 rpm  or either it does not control 1 of them or 2 of them.
having Asus x570-E only using the chasis 1 and 2 fan header and m2 fan header + pump header that i never control, fans have a mind of its own.

**Comment by Rem0o** [comment]
That most likely means something is interfering. FanControl expects to be the only software controlling fans.  Make sure:

1. Fans are set properly in the BIOS (PWM/DC, no curves)
2. No asus software running
3. No other fan controlling software is running

**Comment by Sylvanas-1977** [comment]
I have no idea if i can set no fan curve etc if had it configured with it all at 100% or disabled it seems within software it reports 27% at times when mixed fan curve reports it should be at 24% and the fans report 27% as well i do not have any other software running, it sometimes sattles at 30%

**Comment by Sylvanas-1977** [comment]
I can set it manually to 24% but if the fan curve says it should be at 24% it randomly does not do that im getting seriously frustated there must be a way to get it working the way i want it to work usb fan controller or whatever cos my x570E motherboard is not working the way it should obviously, and its not like if i disable manual control it go's back to 27% it just does not respect the fan curve setup, i have no time for troubleshooting this forever.

**Comment by Sylvanas-1977** [comment]
Scratch that it does not go below 32% randomly while it does ramp up as if internally there is a startup setup at 31,8% even tho its set at 0% for both start and stop i seriously do not understand this software at all, i can setup ipxe network boot and all the fancy stuff, but fan control software clearly is having a configuration issue, refreshing sensors gives randomy results sometimes it works then it breaks next time it go's down the fan curve randomly, like it forgots that its running at 32% still and supose to run at 24%, heck i can manual control and set it to 100% it ramps up like intended then set it to 0% and it gets stuck at 13% and wont go below that, its very inconsistent.

**Comment by Rem0o** [comment]
Keep in mind this software supports hundreds of motherboards via https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.

Most that are supported work great, some don't. Yours might be one that don't. 
For every working boards, BIOS configs can break stuff and other third-party software can break stuff. That makes a thousand reason why "a specific setup" might not work.  I can't fix every single one of them, that's just the nature of it.

Now, 

I've recommended you to take a look at your fan configs in your BIOS. Some people have related similar issues when the headers were set to DC while fans were PWM and vice-versa. If the fans don't follow the curves, it's because something else is overriding or blocking FanControl. In that case, you WILL get inconsistent readings relative to your curves. No config change in FanControl itself will fix this.

Either you got something else interfering ( BIOS config or software ), or consider your setup as not supported. That's it.

Spamming the same message over and over here won't fix your issue.

**Comment by Sylvanas-1977** [comment]
if had it disabled enabled seems make no difference, no other software installed, refreshing sensors gives random results, feels like sensors aren't working fully all the time or something else is going on, it happens when it ramps down  it never happens when ramping up, so going from 100% to 0% it sometimes get stuck at 14% minimum sometimes 27% etc worse case scenario i just get a water temp sensor and try fan curve based on that, but with sensor already on my radiator and temp sensor only ranging from 27 to 30 during idle that randomly go's up i have not much to work with, and ai suite wont even take gpu temp unless its an asus gpu, wish i could just grab usb fan controller that accepts gpu temp and cpu temps maybe other sensors and configure that, is there a way to debug it or something to see if there is an issue somewhere ?

**Comment by Sylvanas-1977** [comment]
Sorry for wasting your time probablyh should just posted this somewhere else, found another solution and it just respects my fan curve now, im thankful for trying this software if i did not i probably would not even tryit other alternatives.
