### ISSUE TITLE
Open Sourcing & a donation

### ISSUE THREAD

**Issue by AaronFriel** [Rem0o/FanControl.Releases#471]
Hey @Rem0o, I donated this morning to support your software, and I hope, to nudge you toward open sourcing it.

I'm certain that if you released the source code, you wouldn't be harmed, and others would contribute to the best fan control software available on Windows.

Thank you, but I would feel _a little bit better_ about running your program with the level of access it has if I could inspect the source code.

**Comment by Rem0o** [comment]
Hi,

First off, thanks for the donation.

There was an issue already on the subject of open-sourcing FanControl, you can read it here: https://github.com/Rem0o/FanControl.Releases/issues/89

My position on the subject hasn't really changed. This is hobby project that I develop when I have time at my own pace, and I'm happy with the way it is going.

If I was to do open-source, I would probably start fresh, with a better foundation, with the same backend but have the whole thing community driven instead of imposing my vision/direction like I did with FanControl.

As for inspecting, all of the backend code that requires admin rights is here: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor.

If you want to toy with your fans yourself, it has everything you need.

For the UI section/FanControl itself, this is a simple .NET program and thus I can't hide anything. I believe you are a software engineer, so if you want to take a look for suspicious stuff, you should know there are plenty of tools to take a quick look inside .NET programs without much restrictions.

If this answer makes you regret your donation, send me an email and I will send it back.

Cheers.

**Comment by quinndiggity** [comment]
Fixed in https://github.com/Rem0o/FanControl.Releases/pull/1629
