### ISSUE TITLE
FanControl stopped detecting one of my case fans

### ISSUE THREAD

**Issue by lay1550** [Rem0o/FanControl.Releases#507]
Been using the software since v99 and since v101 if I'm not mistaken the software randomly stopped detecting one of my case fans.

I've checked the BIOS and Argus monitor to see if the issue might be hardware related but everything seems fine in those. I've tried to downgrade to v100 but the issue now persists. 

For reference my motherboard is the B550 Aorus Pro V2.

Thank you Rem0o!

**Comment by Rem0o** [comment]
If a downgrade doesn't fix it, then that's on your end, something changed in your config.

**Comment by lay1550** [comment]
![dfsdfsdfsdfs](https://user-images.githubusercontent.com/97176167/154077384-c072deab-55b1-485f-8201-52d5e595ac03.png)

Yeah I've tired about 4 different versions the last one being v98 and that only detected one fan for some reason. I've noticed that this system fan is presented in a different ITE from the others in hwinfo is this relevant at all?

**Comment by PrinceLikesCookies** [comment]
Hi @lay1550 , I know you closed this but I've researched a little bit after getting the exact same motherboard as you and reported to librehardwaremonitor https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/662. I don't really understand how nobody really got around to fixing the compatibility issues with this chipset. It's been a problem since like 2020 but I haven't found much info besides a guy posting addresses for the ITE IT8792E. https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/251
Nobody seems to be able to fix this problem and the closest thing is that linux has support for this kind of gigabyte motherboards. Hopefully someone from LibreHardwareMonitor fixes this.

**Comment by lay1550** [comment]
I appreciate the heads up @PrinceLikesCookies, thank you! I'm just glad to know it's not an isolated issue, I guess I'll just use one of the Pump headers using the primary ITE, thank you!

**Comment by lay1550** [comment]
I appreciate the heads up @PrinceLikesCookies, it's good to know it's not an isolated issue. Thankfully I still have one header using the primary ITE (CPU_OPT) so I'll use that header for this fan instead. thank you!
