### ISSUE TITLE
'Start with Windows' task never gets made in Task Scheduler?

### ISSUE THREAD

**Issue by zamazo** [Rem0o/FanControl.Releases#510]
Great software, does more than I'll ever need except the start with windows setting doesn't generate a task in task scheduler?
I tried this on 2 different Win 10 machines and neither worked.
Both machines only have a single local account. 
I placed the folder directly in `C:\Fan Control` for one, and `C:\users\me\downloads\Fan Control` for the other.
One's an asrock mobo, other's a msi one. Both booting from nvme.
From the asrock machine that's actually recently imaged:
![image](https://user-images.githubusercontent.com/99944612/154624605-bd919801-d736-4160-aa4e-90fb7afd40e0.png)
Ticking & unticking the setting does nothing, tho the rest of the program works great.

The setting remains `on` as long as the program's running, minimized or not. 
But if exited, the setting reverts to off.

Any ideas? Other programs using task scheduler like HWiNFO seems to work fine?

**Comment by Rem0o** [comment]
Any logs? (log.txt)

**Comment by zamazo** [comment]
Not that I can see unless I'm looking in the wrong place:
![image](https://user-images.githubusercontent.com/99944612/154743911-374b6fc3-8dd2-41ad-b6e0-9c7eb8e152fa.png)

**Comment by Rem0o** [comment]
Admin account?

**Comment by zamazo** [comment]
I figured out my specific issue.
For whatever reason, this does not work if your computer name and user name matches exactly.

Did another series of reinstalls of windows and kept computer name and user name separate and now this is working fine.

Not sure why this is the only auto-start program affected however.

**Comment by xhul-dev** [comment]
> I figured out my specific issue. For whatever reason, this does not work if your computer name and user name matches exactly.
> 
> Did another series of reinstalls of windows and kept computer name and user name separate and now this is working fine.
> 
> Not sure why this is the only auto-start program affected however.

I've been suspecting that for quite some time.
I'm still convinced the bug comes from the task scheduler itself, cause there was a very similar issue in the past, where admin accounts without password weren't correctly interpreted, but apparently Microsoft fixed it at some point.

I think Fan Control is affected simply because the method it uses to register the task triggers the TS bug.
At least we know the bug can be bypassed, by registering the task the way Hwinfo does, for example.

As far as i'm concerned, I think i'll continue to use the cmd+ps trick for now (https://github.com/xhul-dev/FanControl-WinStart).
Cause i already know changing either my account or computer name will break some stuff deep inside the system.
