### ISSUE TITLE
Hysteresis not working

### ISSUE THREAD

**Issue by devoker666** [Rem0o/FanControl.Releases#514]
I have tried with different sensors and the fan curves ignore hysteresis all the time.

**Comment by Rem0o** [comment]
Just tested, and they do ?

**Comment by devoker666** [comment]
![image](https://user-images.githubusercontent.com/100297930/155350912-652528cc-25d8-4668-93cf-f2d9d4c60be3.png)
I keep trying with different options like setting temperatures to integer values and enabling/disabling hysteresis only to down but can't make it work. When the temp drops from 50 to 49 fans go to 0 instantly and I tried with other sensors and result is the same. I even put a hysteresis value like 25 and still not working.

**Comment by Rem0o** [comment]
Ah, that's because you are playing on the edge of your curve. Hysteresis will be ignored when going down to the min value and will snap to the min value. Hysteresis will then work on the way up.  Same thing will happen at 90 deg, but the other way around., It will snap to the max value disregarding hysteresis, then work on the way down.

In other words:
As soon as you go from > 50  to < 50,  your fan curve will go to 0 disregarding hysteresis.  Going back to > 50 will use hysteresis.

If you want hysteresis to be applied in that minimum value case, simply add another point at like 40 deg at 0 %.

**Comment by devoker666** [comment]
I tried like you said but I think it needs not 1 but 2 more points as you can see in the video.
https://streamable.com/p589qi
I also had to change the adjacent temperature from 49.9 to 49, I think it doesn't work with fractional numbers for some reason.

**Comment by Rem0o** [comment]
In your video, the changes occurs at 49 and 54 which is 5 deg.

**Comment by devoker666** [comment]
That's not how hysteresis is supposed to work. As I only select hysteresis way down, while the temperature was decreasing fan was supposed to stay at 35% until 45 degree (50-5) but in the first 2 attempts it is going to 0 percent at 49 degree. If you look at the 3rd part of the video it is working as intended.

**Comment by Rem0o** [comment]
One thing to note, the hysteresis has in memory the last temperature point it changed the %, not the last stable temperature.  You might be sitting at 54 for an hour let's say, but the hysteresis remembers 51 as the last time it changed the %. So its boundaries for change are then 46 and 56.   That might explain the behavior you are seeing, as you are doing all your tests in a continuous way.

**Comment by devoker666** [comment]
That's what I was suspecting, now everything makes sense. I was thinking the other way because all the fan control softwares I had before was working as I had explained before, so I assumed this would work the same. Still imho, I think it would be better to control the way I explained.
