### ISSUE TITLE
Feature Request:Automatic stop and Support Chinese

### ISSUE THREAD

**Issue by cike-567** [Rem0o/FanControl.Releases#528]
When the temperature is low, the fan can stop. It can not only save energy, but also reduce inhaled dust. I want to add the function of fan stop when the preset temperature is reached.
Can you add Chinese support? I can help translate the text.

**Comment by Rem0o** [comment]
![image](https://user-images.githubusercontent.com/14118956/157923862-a50dcff5-d394-4fcf-b756-f1b0bd47bd9c.png)

Fan stop is already present in two different ways.
Set a curve to 0%, if supported, fan will stop.

Otherwise, use the stop %, and any command below that will snap to 0%, hence stopping the fan.

As for language, I don't plan on doing multi-language, as maintenance would be an absolute pain.

**Comment by cike-567** [comment]
Well, I wish you a happy life
