### ISSUE TITLE
Settings Dropdown occasionally stopping to work on Curves

### ISSUE THREAD

**Issue by TheMasterofBlubb** [Rem0o/FanControl.Releases#580]
Occasionally the Dropdowns, where the Settings of a curve are, stop working properly, as in the seem to miss the GUI elements (the open close animation works).

Seen on Auto, Target and Linear. Not sure what triggers that bug and also not sure if Fan Controls are affected too.

Can be fixed by reloading the whole GUI (aka close window andd reopen from tray icon)

When its bugged:
![grafik](https://user-images.githubusercontent.com/12793716/164511783-e7c8be8a-fa00-446f-8676-6eb9ef23c576.png)

How it should look like:
![grafik](https://user-images.githubusercontent.com/12793716/164512466-198efa0c-fff7-4a90-bc0f-5076ababc992.png)

**Comment by Rem0o** [comment]
Will have to get some steps to reproduce, because I never seen that :/

**Comment by TheMasterofBlubb** [comment]
> Will have to get some steps to reproduce, because I never seen that :/

Yeah i just though about what i did before the bug occured...

1. Collapse the Dropdown
2. Move that Box (either directly or indirectly by reordering)
3. Try to open the Dropdown

Also just tested same issue on ALL Dropdown of all Boxes

**Comment by Rem0o** [comment]
Got it. 

It's the expander in the card being unloaded then reloaded into its new position which gets messed up. Don't really know why but I can't even get it to get back to normal. All of its properties get messed up.

Instead of moving the card, will actually delete it, then create it back into its new position. Avoids weird bugs like this one.

Thanks!

**Comment by TheMasterofBlubb** [comment]
Thank you very much and NP
