### ISSUE TITLE
Small bugs with fan control 

### ISSUE THREAD

**Issue by Samm223** [Rem0o/FanControl.Releases#632]
Good morning, 

I know you are the one who creates just the UI but I just want to report a bug where 2 case fans wont allow control but show an RPM reading so it wont pair with anything. trying manual control will change percent but not fan speed. also wont allow Corsair PSU fan control and only shows RPM. If this is something you cant fix please let me know where to place this so hopefully itll get resolved. 

Thank for the great software, its in early stages but i believe this could easily outpace major companies with a little updates and bug fixes. 
![Screenshot 2022-04-23 123424](https://user-images.githubusercontent.com/104272293/164920798-e042d171-6dd9-4622-aca2-4ed5d4bb3f37.png)

**Comment by DfrostX** [comment]
Its not a bug, its because fan control of that MB controller is not supported by LHM. Same for the Corsair PSU.

Please refer to the Readme:

I am not the main developer for the driver/backend portion of this software. Fan Control is basically a UI on top of existing hardware libraries. Any issue regarding hardware compatibility entirely depends on:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor
https://github.com/falahati/NvAPIWrapper
Please only open issues for the software itself, UI, feature request and so on.

**Comment by Samm223** [comment]
I received these errors after 111 update, also after update save file was reset to default

![Screenshot 2022-04-23 124507](https://user-images.githubusercontent.com/104272293/164933830-ff36d8e3-84d1-4524-a573-1c9e76a2890d.png)
![Screenshot 2022-04-23 124535](https://user-images.githubusercontent.com/104272293/164933831-c57371e3-0af9-48e5-bcb2-7ee707155d5c.png)

**Comment by DfrostX** [comment]
Some sensors got disabled.

What is enabled (ticked) in the sensor settings from the menu (3 dots top right -- sensor settings)?

**Comment by Samm223** [comment]
had to restart the program, the update must have caused an issue where it didn't save my config. now my case fans don't change rpm even with then being manually paired with the proper controls. also with my AIO installed on the AIO header it doesn't come up in the list which i know isn't on this Author but i hope these can get fixed for everyone. right now its not a big deal as the CPU and GPU are coming up correctly and able to be controlled
