### ISSUE TITLE
Cannot manually set the GPU Fan 1- 3060

### ISSUE THREAD

**Issue by Dan017** [Rem0o/FanControl.Releases#636]
Hello. I have a 3060 with only 2 fans and i have configured the temp graph and was about to apply it to the GPU Fans, but i can manually  adjust only 1 fan of 2...i dont seem to understand...maybe an unninstall will do it or i dont know. Open for suggestions. Thank you in advance.

![Fan Control V111 (userConfig json) 23_04_2022 21_27_07](https://user-images.githubusercontent.com/104276294/164943682-e98880e0-db51-4f67-9b85-fec78abfe8d1.png)

**Comment by xhul-dev** [comment]
Hello there.
The influence of Fan Control of GPU fans is limited, so in practice, you can expect strange behaviours.
I have a 3060 with 2 fans aswell, and the RPM doesn't always follow what Fan Control sends to the fans.
I suggest turning off the control on all GPU fans, mostly because the curves used by the GPU BIOS are already designed so that the fan activity is accurately relative to the GPU temp.
Cheers.

**Comment by Dan017** [comment]
Thanks for the tip

**Comment by Dan017** [comment]
> 

To be honest, since i have this program, the gpu temp has decreased while in full load... I dont know exactly if it s because of the gpu temp thing customization OR because the case fans actually work at a faster speed

**Comment by xhul-dev** [comment]
The case fans (on your hub) may be involved aswell, especially if their activity is dependant on GPU temp in Fan Control.
