### ISSUE TITLE
V112 broke fan control (silently stops fans)

### ISSUE THREAD

**Issue by Nightinggale** [Rem0o/FanControl.Releases#720]
I had a setup with v111, which worked as expected. It asked if I wanted to upgrade to v112 and I clicked ok, it restarted and now the fan controllers can't be controlled.

When the CPU fan is disabled, the system takes over and it reports RPM as expected. When enabling it jumps to 0 rpm within 1-2 updates regardless of selected curve. I even tried a flat curve at 50% and this went to 0 rpm even when the system set it at 47-52%. Same result with 30%, 70% and 100%. Occationally it spikes for a single reading before stopping, like going 800-1100-0 RPM when it was supposed to drop to like 500 RPM. I have opened the computer and verified that the CPU fan does indeed stop.

Case fan control is dead in another way. Enabling it has no effect on fan RPM. GPU fan control seems fine though.

Auto pairing obviously doesn't work, but auto pairing and threshold setup worked earlier this week (v111). Downgrading to v111 didn't fix the problem, nor did rebooting. This would indicate that I somehow corrupted a setting, but I disabled starting at startup, rebooted and started with a fresh v111 and it still didn't work.

No error report. FanControl doesn't view this as errors, nor does it give any indication to what might be wrong.

**Comment by broconut123** [comment]
i'm getting missing sensors/controller errors. Sometimes it works, but it reports no rpm information.

**Comment by Nightinggale** [comment]
Looks to me like #722 #725 and #726 are all caused by the same issue as this issue.

I tried downgrading to v111, v110 and v100. All have the same issue now, but I managed to use v111 just fine just a few days ago.

**Comment by Sejiko** [comment]
I have the same problem after the updater exe upgraded to v112  my config wouldnt work anymore and now im stuck with default, also the refresh prozess wont work anymore so im stuck with defaults.

**Comment by Rem0o** [comment]
Does it only happen when you use the instance that started with windows? If you exit out, right click run as admin, same issue?

**Comment by Nightinggale** [comment]
Happens with any instance, being startup or executed later. Explicitly running as admin makes no difference. I used task manager to ensure no process was left behind behind when trying again.

**Comment by Nightinggale** [comment]
I have an update. I cloned my boot drive a month ago and the clone haven't been online since. I took my computer offline, replaced the boot drive and then both v111 and v112 can suddenly control the CPU fan again where changing curve/controller settings adjusts the fan as expected. Replacing the boot drive again to the online (hence updated) one and neither v111 or v112 works. Both stops the CPU fan if I try to set it to anything.

So same hardware, same OS, same settings. The only difference is that the broken one is online and self update. I checked anti-virus too, though this didn't seem to have any effect either (clone has the same anti-virus with the same settings, just not updated).

I kind of suspect this could be an ASUS driver issue because so far it has been confirmed to affect:

- ASUS PRIME X570-PRO (my motherboard)
- ASUS ROG STRIX B550-F GAMING (WI-FI) (screenshot in #726)

Right now I'm out of ideas on how to investigate this further. I tried killing various ASUS processes, though that didn't help. That doesn't mean I will stop thinking about how to try to figure out how to investigate this further.

**Comment by DeliciousDemon** [comment]
I have a similar problem, also with an Asus motherboard - H470M-PLUS. Running Windows 11 21H2 22000.613.

I'm not sure exactly when it started happening, just that I had a CPU overtemp warning on a reboot last Sunday, and saw that my CPU and case fans were randomly stopping and restarting regardless of curves/temperatures with Fan Control running.

I updated Fan Control to 112 in the hope it would solve the issue but it didn't.

I hadn't updated any Asus software for months, and according to Windows update history no updates for a couple of weeks - so it's a bit of a mystery what changed or when.

Net effect is I can't use Fan Control at the moment - which is a real shame because it's been fantastic for the last 15 months or so.   I don't think it's a Fan Control problem, but I'm hoping it can be solved in the Fan Control code - I don't have much confidence in getting any support from Asus or Microsoft.

cheers

DD

**Comment by DeliciousDemon** [comment]
That is indeed how it looks.  It's possible it was the last cumulative update for Win11 (KB5012592) and I just didn't notice anything for a couple of weeks, but I'd done quite a bit of gaming during that time with no apparent issues - and was only streaming a video on Sunday when my CPU started to cook.

The idea that Asus could push something so significant out without me/us being at all aware of it is disconcerting - and to be honest I think it's unlikely.

Only other thought is I moved to Bitdefender a couple of months ago and that silently updates - not sure how likely it is that Bitdefender is a factor.

Understood that it's tricky for you to tackle and not at all proven to be a problem with your code. Since you're obviously reading here, Rem0o, I'll take this opportunity to thank you for your excellent software - I love it, and look forward to being able to use it again when possible.

**Comment by DeliciousDemon** [comment]
Interesting.... problem seems to have gone away!

I've re-run Fan Control having not used it for a couple of days, and it seems to be fine now - certainly no issues with fans stopping & starting. Case fans are following GPU as they should. 

I did run Asus's awful ArmouryCrate a couple of days ago, which then updated some components, just so I could set fans full blast for gaming - so that could be a factor - but I hadn't run it for months before the problem began.

I'll update after a reboot with Fan Control set to start with Windows, just in case that does turn out to be relevant.  Whilst I was having the issues it didn't seem to matter whether it was run manually or at startup.

So, pleased to have it back - though will be watching my temps carefully for a while.

**Comment by Nightinggale** [comment]
> Interesting.... problem seems to have gone away!

Reading this I opened ArmouryCrate for the first time in ages. Unsurprisingly it told me that there was an update available. I updated and nothing changed. I learned that there is a "check for updates" feature in settings->updates and it found a bunch of components, which could be updated despite just having updated ArmouryCrate. I updated all and now it seems to be working.

Since multiple people encountered the same problem around the same time, my guess is that ArmouryCrate updates components once in a while, but not each time the computer boots. Some components were updated just hours ago so let's assume the fix is in one of those. If so no more people will run into the problem. Also next automated update will fix the problem for everybody, though manually requesting an update will fix the problem right away. This however is speculation because ArmouryCrate doesn't say anything about auto updating. It's just that if it doesn't do that, then it makes no sense that multiple people run into the problem at the same time if it's caused by a bad update.

It has become very clear that the bug came from ASUS and not FanControl. Poor Rem0o. Looking into what could have caused all the bug reports and nothing makes sense compared to recent changes. It just got worse by the fact that it apparently by chance was perfectly timed with the v112 update.

**Comment by Rem0o** [comment]
@Nightinggale  That's part of the "fun".  ;)

Please close.

**Comment by DeliciousDemon** [comment]
Thought I should dive in before Nightingale closes the ticket - just to confirm that Fan Control is still working fine today, having started up at Windows boot.

**Comment by bananacles** [comment]
I am having the same issue, my motherboard is an ASROCK b365m Pro4. I started using fan control last week, I'm on v112. I have a graph curve that only one of my fans ignores. With the curve on it never spins, when I turn off the curve it manages itself properly.

Would you recommend downgrading to a specific version or checking for driver updates for my motherboard? I don't think I have any other programs managing my fan speeds, if there's a list of known programs that interfere I'd appreciate a link to it.

**Comment by Nightinggale** [comment]
> I am having the same issue, my motherboard is an ASROCK b365m Pro4.

Asrock split out from ASUS in 2008. No idea if they cooperate after that, but my best guess is that you should look into updating every single Asrock software you have. If ASUS has a problem, which they fixed with an update, Asrock would likely also be able to fix it with an update.

If both have this issue, then it sounds like the bug is from before 2008, but then why haven't it been an issue until now 🤔 

> I have a graph curve that only one of my fans ignores. With the curve on it never spins, when I turn off the curve it manages itself properly.

Yeah that sure sounds like this issue. For good measure make a flat curve at 100% and assign that curve to the controller in question. If it stops when set to 100%, then you have run into the same issue.

I will close this issue once the Asrock issue has been fixed or a dedicated Asrock issue has been opened.

**Comment by bananacles** [comment]
Yup, flat curves don't work either. I could be mistaken about the behavior here but it seems like it works if I switch to the curve while the fans are spinning, but once they stop they don't start up again. I'll update bios and see if that helps.

**Comment by Nightinggale** [comment]
No updates on the ASROCK motherboard. I consider this issue solved and if anybody still suffers from stalled fans then go open a new issue.
