### ISSUE TITLE
Fan goes down after manually setting or curve setting

### ISSUE THREAD

**Issue by ilcanegamer** [Rem0o/FanControl.Releases#754]
So let's say i put the fan speed at 60% 4 seconds later it returns to 37% and i don't know if it's a problem on my end or with the software.

**Comment by Rem0o** [comment]
Something else takes over. Can be your bios, or an other 3rd party. Make sure your bios has no smart control enabled.

**Comment by Slurmie** [comment]
Hi, I have some similar problems. On some fan headers it works, on others it just stays in speed I set in the bios. 
I have GB aorus z390 master mainboard and I already removed the SIV software (the original software for fan control). I googled a lot without success. 
Do you know how to deactivate these "smart controls" on my mainboard or are there know issues with it?
Looking forward to actually use your software and donate :)

**Comment by ilcanegamer** [comment]
It's a HP bios and it does not have any fan controlling software

**Comment by Slurmie** [comment]
> It's a HP bios and it does not have any fan controlling software

What do mean with that? In the bios is option called smart fan 5. When use an other Software than SIV on Win10, it falls back (not on all fan headers) to the bios settings and I don't know how to turn this of.

**Comment by EvoGuyIX** [comment]
> > It's a HP bios and it does not have any fan controlling software
> 
> What do mean with that? In the bios is option called smart fan 5. When use an other Software than SIV on Win10, it falls back (not on all fan headers) to the bios settings and I don't know how to turn this of.

I have a Gigabyte board too, Z390 Pro Wifi, and it's unfortunately a nightmare. I tried uninstalling SIV, setting bios control as 'off' as possible and it was horribly unreliable. Had to stop using Fan Control because of the irregular behavior. 😔

Unrelated but I was having a  bug with my 3070ti where it absolutely would not hold onto the auto-stop. It would put the Nvidia Experience software into manual mode, for which 30% is the minimum. This is an Nvidia problem mostly I'm sure. 

Hopefully in coming months, things will get me able to be back on board!

**Comment by Slurmie** [comment]
Sad to hear that.. Then I will sadly stick with SIV.
Hope we'll have more luck with next MB. 😄   Always kind of a lottery with does mainboards.
