### ISSUE TITLE
Closing the window doesn't trigger the save settings modal, and it doesn't close.

### ISSUE THREAD

**Issue by ivancuric** [Rem0o/FanControl.Releases#782]
When I close the window I no longer get the "save config" confirmation dialog, and I have to press close a second time to close the window.

Running v114 on Windows 11.

**Comment by xhul-dev** [comment]
I can confirm that.
That only happens if you actually made some changes since the last configuration save (if none were made, the app successfully goes to the system tray when clicking "X" once).
Also, probably a side effect: if the app is in the system tray (GUI closed), and there are some unsaved changes, selecting "Exit" opens the GUI instead of exiting.
