### ISSUE TITLE
fans come up paired with "none"

### ISSUE THREAD

**Issue by Samm223** [Rem0o/FanControl.Releases#799]
2 lower case fans I cant find what they need to be paired to. I've tried to manually connect them but i cant control them even when all of them are connected to the MB.  also when all are set to mixed they all dont sit at the same percent. its gone through a few revisions and still havent seen a fix yet. my MB is a Z590 Aorus Master

**Comment by Rem0o** [comment]
Compatibility issue. 

See README.

**Comment by vincesmits** [comment]
Hey @Rem0o Can you help me out or guide me in the right direction. I too have a Asus/Aorus Z590 Motherboard and have populated every fan header on the board. 5 Of the fans work and show up in fan control, but 3 of them don't. I have already tracked the issue down to the following reason: The fan headers seem to be connected to a second chip. I know you use LibreHardwareMonitor but to me it seems the issue is not there, or at least it is able to show the controls and rpms. 

Is fan control able to communicate with this second chip through LibreHardwareMonitor ?

I would love to somehow fix this issue for myself and also because the Asus/Aorus Z590 is quite a popular chip, i think a lot of people are running in this issue. I am able to provide resource related to the z590 board if needed.

**Comment by Rem0o** [comment]
Can you actually control these 3 fans with LHM? Btw, it's not the chipset has nothing to do with controlling the fans, it's all about the "SuperIO" chip, Nuvoton, ITE or whatever.
