### ISSUE TITLE
Suggestion - Automatic config file at a certain time 

### ISSUE THREAD

**Issue by avexlol** [Rem0o/FanControl.Releases#8]
Would be dope if you could make it so you can set a config file to be applied at a certain time! I can see it being used for example if you want to keep your PC overnight to download something, but don't want to hear any fan noise and you would just be able to make a config with all fans at 0% and make it apply at a custom time.

**Comment by beezley** [comment]
Just a suggestion, I would imagine you could possibly setup something in task scheduler to do that.

**Comment by Rem0o** [comment]
> Just a suggestion, I would imagine you could possibly setup something in task scheduler to do that.

Yup, that would be a simple way to do it.

**Comment by AdrenalinaGit** [comment]
Yes, it appears (based on only several days of experience) that Task Scheduler can safely stop & start FanControl tasks.  I wrote a .bat file that stops & starts FanControl tasks (which set the speed of an external fan that's cabled to a motherboard fan header) based on the temperature of my USB-connected external drive.  Each of my tasks is associated with a separate copy of FanControl, each in a different folder, each with its own config file (set to a different flat curve and with only the external fan control enabled).  You could make each of your config files whatever you desire.  Just be sure to have the copies of FanControl in separate folders so they won't overwrite each other's CACHE files.

OP, you may need two separate copies of FanControl (with corresponding tasks in Task Scheduler) to do what you say you want.  However, I haven't researched whether FanControl restores BIOS control over the fans when FanControl is stopped by ending its task.  If it does reliably restore BIOS control, then a single copy of FanControl and a single Task Scheduler task should suffice... in other words, you could use Task Scheduler to stop & start the FanControl task and the BIOS controls would activate when the FanControl task is stopped.

Note #1:  To be able to stop FanControl using its associated task, my experience is that the task needs to modified so that its startup action doesn't use cmd.exe to launch FanControl, and instead launches (the copy of) FanControl directly.

Note #2:  It appears to also be possible to have two (or more) separate copies of FanControl running simulaneously if each copy enables only a non-intersecting subset of the fan controls.  In addition to the FanControl copies for my external fan that my .bat controls so only one of them at a time runs, I also run a separate copy of FanControl nonstop that manages my internal fans.
