### ISSUE TITLE
Feature Request: Add a button to control whether to automatically check for software updates

### ISSUE THREAD

**Issue by youtehub** [Rem0o/FanControl.Releases#808]
The software will be detected and updated every time it is started. I hope there is a switch button to choose, so that I can decide whether to check whether to update the software every time I start it. Instead of this, every time you start, it is forced to check for the latest update.
Since the network here is not very smooth, and occasionally unable to connect to github, a pop-up window will appear, so I hope a button can appear to avoid forcibly checking the update every time the software is started.
Whether to force check for updates should be left to the user to decide, not the software to force it every time. Attach a screenshot, the pop-up window that will appear every time the network check fails.
[](https://img-blog.csdnimg.cn/4f8abc2de8484d3bbc7bed5cf9082ff3.png)

**Comment by youtehub** [comment]
![](https://img-blog.csdnimg.cn/4f8abc2de8484d3bbc7bed5cf9082ff3.png)

**Comment by Rem0o** [comment]
That's a fair demand. Will add an option to opt-out. Will be set in the CACHE file, won't be per config file (json).

**Comment by xhul-dev** [comment]
> Alternative idea would be to remember the CURRENT version, and never notify until you change version manually. Though if I allow that, a lot of folks will end-up out of the loop for newer updates....

Personally, i would go for the good old "check for updates at startup (recommended)" box in the general menu.
If the box is checked by default on first run, i believe you'll still get a decent number of people staying up2date.
Your call.

**Comment by Rem0o** [comment]
I guess we have 2 things here:

1) OP has spotty internet connection, and doesn't want an error message every time the software starts because it couldn't look for the version info on the server => Solution is to not show that error message on the auto-update check at startup. That message should still appear when you manually ask to check for update.  That I will do.

2) Some people will want to stick to an older version because it works for them. These people don't want the popup every time they start the app because they don't have the latest version.  For those guys, I will add a "Disable this popup for the current version [YOUR_CURRENT_VERSION_NUMBER]", which will stop the popup for your version, let say V105, until you change version again manually. Until then, no popup ever.  If you update manually and want to stick to that new version like the previous one, you'll have the check it again for your current version when the popup shows again. I feel like that's simple enough and should satisfy people who stick with a specific version.

**Comment by Rem0o** [comment]
Implemented.
