### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by vyressi** [Rem0o/FanControl.Releases#816]
This project uses libraries that are licensed under GPL 3.0, MIT, and MPL 2.0.  

The source code is not published in this repository, and it is unclear which license(s) this repo is being released under. 

Kindly clarify.

**Comment by Rem0o** [comment]
I fall into this category for FanControl itself:

```
You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. 
```

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license

This is only a release repo, the actual source is closed. 

As for the libraries, if I read correctly, they require me to disclose any change to them, and provide their source. I didn't make any change to them, and I linked in this repo's README and from the software's side menu.

By the way NVAPIWrapper is LGPL-3, not GPL. LGPL limit the copyleft obligations to modifications to the library itself. Wouldn't use it otherwise.
