### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by simonporte** [Rem0o/FanControl.Releases#83]
Hello,

From the absence of license in the repository, I guess your software is under proprietary license (copyright) ?

Can you write it explicitly somewhere? Perhaps add a `license.txt`

Any plan to open source the code ?

Anyway, I'd like to thank you for this software, it is the perfect replacement for Argus monitor (nagscreens in trial versions) and speedfan (really not straightforward).

Regards.

**Comment by Rem0o** [comment]
Well FanControl by itself is not open-source, so I don't really know what kind of license I should put in there.
From https://choosealicense.com/no-permission/, leaving blank defaults to no-permission, which is the state of this repo as of now. Perhaps I should add such mention at the top of the readme?

**Comment by simonporte** [comment]
First, when I saw there was no source, I searched for a second repo with source (the repo is called release, so I thought there was a second one for source, it is not so uncommon), it is a bit misleading.
Second, when you publish on github, anyone can fork and so on (and so did 10 persons).
So most will assume the code is open, but it is not always true.
A simple copyright mention in the readme would be sufficient, explicit and not too blatant.
It is just a matter of not letting people having wrong ideas about the license, in my case I thought for months it was fully open source just because it was on github, I think other would do the same mistake.
Not a criticism or anything, even if I think it would be a great thing if such a piece of software was open sourced someday.
Regards.

**Comment by fauder** [comment]
> Second, when you publish on github, anyone can fork and so on (and so did 10 persons).

They really shouldn't. If there is no license specified, it is copyrighted by default.

**Comment by MeikTranel** [comment]
> If there is no license specified, it is copyrighted by default.

That's not how any of this works.

As a matter of fact: You are depending on a MPL-2.0 and a LGPL-3.0 library. Both of which require licensing works to be open source. LGPL-3.0 even requires your derived work to also be licensed LGPL-3.0. You are in gross violation of these terms. Just letting you know.

**Comment by Rem0o** [comment]
@MeikTranel 

As far as MPL-2.0 (LHM), if I read everything correctly ( I might not ), I need to disclose its source right? I have a button in the software which redirect to the LHM repo, but I guess a proper "About" section would be more appropriate.

As for the "GNU Lesser General Public License v3.0" (NVApiWrapper) license, again, if I read correctly, the source must be disclosed, and any "change" to the code must be the same license. However, I made no change to any of these dlls myself. You can literally compile them from source and copy then in and everything will work the same. Again, wrapping all of this in a nice "About" section would make a lot of sense.

I want to do this right. What exactly would you suggest on top of a proper "About" section in the software?

**Comment by MeikTranel** [comment]
Slight Walkback - yes you are right you are allowed to link a lgplv3 lib without disclosing your own source. You are in still in violation right now since as far as I can see you do not include license and instructions with - your distribution. Very technically speaking you'd have to include the actual nvapi source code with your install but I'd reckon you can get away with linking to the source and copying the license text. That's what most android apps seem to do - list per dependency:

- Name
- sourcelink with Sha/tag of exact version
- full copy of license text

It has to be accessible from within the app - i would just create a couple of markdown files with that information (one per licensed lib) and link/copy them for the GitHub readme / the install itself.

One thing I would like to tell you in the end is this: if you're already nihilistic about people running ilspy over the app to look at the actual code, i would really recommend you to just publish the entire source. Nobody is gonna make fun of you, nobody will give you shit about some random design decisions. On the other hand there is so much to learn from another set of eyes. 
Unless your source code contains the Unabomber manifesto open sourcing the full code will in 99.9% will improve the project in the long run, give confidence for people geeky about running hardware level code with admin access and makes life easier for everyone involved. At least a couple hundred people think your code is neat so worrying about what people would think of your code is an exercise in futility.
