### ISSUE TITLE
Auto Fan Curves:  Can we please get the old logic from v115 back? 

### ISSUE THREAD

**Issue by abqnm** [Rem0o/FanControl.Releases#832]
Or at least have an option to use one or the other?  The new "linear" profile logic basically made all of my auto profiles useless since now the fans don't try to maintain the idle temp, and instead barely scale above minimum when above idle, and then when it gets to the load temp, goes to the max speed.  At least for how I'm using them, the new logic just doesn't work.  Thanks!

**Comment by Rem0o** [comment]
I don't quite understand how you use the auto.   The only difference I made is that instead of having a big step from around the idle temp to around the load temp, there is a linear scale.  At load, it acts the same, and at or below idle, it acts the same.

Maybe "idle" is not a good term for that specific parameter. Idle temp should be the upper limit of your idle "zone", where above that limit, you are considered "out" of your idle temp zone.

**Comment by abqnm** [comment]
I've been using Auto curves to keep my chipsets within a range (small form factor systems present more unique challenges than full size ATX systems), while also managing noise. The chipset fans are annoyingly high pitched due to their small size. I found that the original logic worked perfectly for my needs. I had tried every curve type previously, and can do an okay job with a graph, and thought a target would be more ideal, but it doesn't quite work like I need and runs way faster than I'd want for most scenarios. The automatic in v115 was perfect for this application. 

I have it configured with a very narrow range, which may be part of why it responds the way it does. 55C "idle" and 60C "load" with a min/max of 25%/100%, 5%/sec, 3sec response, 3C deadband. 

On the old logic, this would only run the fan at 25% when the chipset falls to 55C or below, and when cooling down from a load, when it got to 56C, it would still be running 43.6%, which would cool the chipset in a few minutes to 55C where it would drop to 25% as expected. 

Now, with the exact same settings, 55C or below still runs 25%, but 56C runs it at a measly 26.9%, which on this tiny 35mm fan, is not enough of a change to do anything at all, and the temp slowly creeps up, until it hits 57C and jumps to 66.7%. So when it's cooling down, it slows down the fan way sooner than I'd expect, which prevents it from ever actually reaching the idle temp and dropping to 25%, on the way down. 

Adjusting the deadband down to 1C does alter the behavior a bit, and brings it slightly more in line with how it was before, but it's also now responding heavily when the temp goes up by 1C, which isn't what I want. I wanted it to only respond after it changed by a couple degrees, then cool it to maintain the load temp while in use and when the cooling demands lessen, to cool it to idle.

So that's why I asked if it would be possible to get a choice of logic types for the auto curve, or go back to the old logic which actually pushed harder toward the idle temp without having to use a 1C deadband that causes more frequent increases just to make it sort of function the same on the way down.

Thanks

**Comment by Rem0o** [comment]
I tested your exact setup:
![image](https://user-images.githubusercontent.com/14118956/170878846-9b0fd02e-0421-439a-b3e9-53f00ab68a5f.png)

With 56 deg, it goes to 40%, not 26.9? 
For the specific logic you describe, If I were you, I would use a graph, with one-way hysteresis:
![image](https://user-images.githubusercontent.com/14118956/170879187-4b4299e0-1587-4aa3-83b4-ef384aa40068.png)

Use a 3 or 4 deg hysteresis, with the one-way checkbox ticked.  It will hold its high% until it drops 4 deg or hit 55.

**Comment by abqnm** [comment]
Not that I don't believe you, but in actual use it works quite different.

![FC auto curve](https://user-images.githubusercontent.com/9168981/170880014-ee1fcb69-05cc-4f0d-997e-a178c55aea91.png)

As you can see, 26.9% when it's at 56C, still.

I've used graph curves in the past (I build 3-4 systems a month), but I found that your original auto curve just worked perfectly for managing both noise and thermals on the chipset fans, far better than any graph I could come up with. Because the point is not to run the fan as fast as possible unless it happens to get to 60C, which it usually won't (58C is generally where it lands), and then keep it between there and 55C.

I've tried graphs very much like what you suggested, and countless other variations, hysteresis in one or both directions, and couldn't come out as perfect as the original auto curve could for both thermal and noise management.

**Comment by Rem0o** [comment]
Ok I think I figured out the 26.9, and that might help you. That behavior was there from the start.

The following behavior did not change from previous versions.

Basically, the auto works with 2 states: Under load, not not under load. 

The following logic did not change:

The "under load" section is [max temp - deadband, max temp]. It assumes it is in those temps because the system has a load, hence the heat. It also expects that if such load is gone, the temp will drop by itself eventually, at least out of the load range. 
In your case, that's [57, 60]. In that mode, the curve will look at the trend of the temperature ( going up or down ) and will try to keep as low of a % to stay in that [57, 60] range.  As long as the temp is stable in that range, it will try a bit lower until it notices the temp wanting to go up, then it will stabilize. In your case, since the range is so low, I believe after a load scenario, at idle it will stay in that higher "load" range of temps (like 57) for a long time, hence the auto pulling it down, until it stabilize, in your case, down to 26.9. When it hits 56, out of the load range, since it's a 1 deg change, the deadband acts as a hysteresis, so it will not trigger a change, and keep the current % until a 3 deg change occurs, or hit idle temp (55).   That logic doesn't play well with small ranges.

The part that changed is the following, I don't mind sharing the code:
![image](https://user-images.githubusercontent.com/14118956/170881934-b28b7421-3bf8-4da4-afa7-c782ee2880aa.png)

In your example, __you did not trigger the hysteresis/deadband__, so even the old logic wouldn't hit the line 287, as 26.9 is proof you did have the slope calculation; it is the previously set % in the "_underload" state (which you can't see the code, but you get the point).

Conclusion: The "auto" part of the curve is only between 57-60, which in your case, IMO, is too wide, as 57 deg might not be a "load" temperature.
You should probably lower the deadband to 1 or 2 deg, to make the load scenario more narrow and explicit.  
From my end, I think when going from "underload" to not "underload", the hysteresis should reset, hence trigger at least once into the "dumb" logic. I will make that change, and it *should* fix your issue..

**Comment by abqnm** [comment]
That fully makes sense and would explain the behavior I'm seeing, and why when changing to 1C deadband it seems to react more like what was happening in v115 (aside from going up a little sooner).

I think your suggestion of 1 or 2 sec on my end coupled with the change to have it reset the hysteresis when transitioning from underload to not underload on your end would likely work out perfectly.

Thanks so much for your analysis of this issue!

**Comment by Rem0o** [comment]
See V117.

**Comment by abqnm** [comment]
Thanks! V117 seems to do exactly what I need. It responds better in the very narrow range I'm using when the temperature is falling back down to idle. 

Closing.
