### ISSUE TITLE
Windows 10 blocking memory access

### ISSUE THREAD

**Issue by realsmoky** [Rem0o/FanControl.Releases#837]
Since the last update, I am receiving a warning. What does it mean and what am I supposed to do? 

![FC](https://user-images.githubusercontent.com/83909336/170985166-1108ccdc-046e-4c81-b8b3-2c1c11f69012.jpg)

**Comment by renesdk** [comment]
Under Actions you should allow it to run. It's basically Windows 10 saying that it's not sure this is a program (FanControl) that should be allowed to run from your hardrive for security reasons.
This mostly happens when a program is trying to run from your user profile folders (like documents or downloads etc).
