### ISSUE TITLE
I cant delete a file of fancontrol.

### ISSUE THREAD

**Issue by shhwepps** [Rem0o/FanControl.Releases#841]
i deleted everything but one file. i dont remember its name because i changed its name. i restarted my pc but it still says "cannot delete the file because it is open in system"  anyone experienced this?

**Comment by crk-gcg** [comment]
Hi! I'm having this issue im my PC. Fan Control stopped working a few days ago, and today I tried uninstalling the program and installing again to see if would fix the issue but it did'nt. Then I uninstalled again, and notice that a few items of the file directory stayed there, so I deleted manually, but the FanControl.sys file won't delete because Windows says that is running in another program.

I tried following the steps mentioned above. Went to the Task Scheduler to see if there was a "FanControl" in the list but, there ins't one.

I also tried reinstalling and running the program to see if FanControl would appear on the Task Scheduler, so then I could delete it and then be able to delete de FanControl.sys first and after uninstall the program, but also did'nt work.

I'm wondering if this issue is related to the fact that the program is no longer working on my PC.

Is there anything I can do to fix this problem?

Sorry about the grammar, english is not my first language.

**Comment by Rem0o** [comment]
Rename the file. Close your user session and/or reboot. You will then be able to delete it.

**Comment by Rem0o** [comment]
@crk-gcg  any crash event for FanControl in the EventViewer?

**Comment by crk-gcg** [comment]
Never used EventViewer before. But I have found this: 

Faulting application name: FanControl.exe, version: 214.0.0.0, time stamp: 0x674f0000
Faulting module name: atiadlxx.dll, version: 32.0.12019.1028, time stamp: 0x670985c5
Exception code: 0xc0000005
Fault offset: 0x0000000000062bd3
Faulting process id: 0x338c
Faulting application start time: 0x01db7f9d5572d8ea
Faulting application path: C:\Program Files (x86)\FanControl\FanControl.exe

**Comment by Rem0o** [comment]
Your amd driver is out of date. Do a clean install of the newest version.

**Comment by crk-gcg** [comment]
It worked. Thankyou very much!
