### ISSUE TITLE
Updater.exe - This application could not be started when trying to update versions

### ISSUE THREAD

**Issue by pseudobacon** [Rem0o/FanControl.Releases#864]
As per the screenshot below:

![image](https://user-images.githubusercontent.com/12183854/172687153-3301ad5a-7d24-4afb-aa58-220a024776c0.png)

**Comment by Rem0o** [comment]
Have you clicked yes? Any logs?

**Comment by pseudobacon** [comment]
When I click Yes it just takes me to this page https://docs.microsoft.com/en-gb/dotnet/framework/install/application-not-started?version=(null)&processName=Updater.exe&platform=0009&osver=6&isServer=0&shimver=4.0.30319.0

Is there a log file somewhere that I can upload?

**Comment by Rem0o** [comment]
Got .NET 4.8 installed?

**Comment by Rem0o** [comment]
@Micke3rd.

The updater is literally 20 lines of code. It's a 1 click to update deal.  Not much effort put into it.  Supporting and maintaining different sw stores like winget, chocolatey or whatever will just add complexity imo. I prefer to maintain a single way to update the software, in this case being this github repo.

**Comment by Mikecom32** [comment]
I just ran into this error as well. If you look at OP's provided screenshot, the path to the program that is run is `c:\windows\system32\updater.exe`. I suspect recent versions of fan control are calling `updater.exe` without providing a path, and since the process is running with elevated privileges, the search path starts at `c:\windows\system32`, rather than the FanControl directory. 

@Rem0o - is this plausible?
