### ISSUE TITLE
[Feature Request] [BUG] Make FanControl an executeable installed on the computer, unstalling not work, can't start GUI two times

### ISSUE THREAD

**Issue by ThimoDEV** [Rem0o/FanControl.Releases#878]
Right now If I want to start the Fancontrol software, I have to search for the FanControl.exe in my explorer, or use a shortcut. 

I encountered a few annoying things while using this software for the past weeks. 

- If the software is started and closed by the [X] close button, the software still runs in task manager. This is desired but I can't start the software GUI again when I double click the executeable. I first have to kill FanControl in task manager.

- Often the software loses its sensors or does a reset. This is already reported by multiple users.

- If I want to remove the FanControl software (for resetting behaviour for example) I have to go into windows safemode because there is one file in register I think that is always running and can't normally be deleted.

Suggested improvements:

- Make FanControl software installable on the computer. So that I can just start it via windows start.
- Add an uninstaller so I don't have to go into safe mode to uninstall myself.
- Fix closing FanControl and not being able to start the GUI again ( separate the FanControl instances in some way, I know SnapCamera has a very similar feature). 

If theres some way I could help with this I'm happy to help!

Appreciate the effort you put into this software!  @Rem0o

**Comment by Rem0o** [comment]
> If the software is started and closed by the [X] close button, the software still runs in task manager. This is desired but I can't start the software GUI again when I double click the executeable. I first have to kill FanControl in task manager.

There is a tray icon. You can open the software GUI back from there.

> If I want to remove the FanControl software (for resetting behaviour for example) I have to go into windows safemode because there is one file in register I think that is always running and can't normally be deleted.

Simply three dot menu exit or exit from the tray icon. Killing the task in task manager will leave some ressources undisposed.

**Comment by ToXiCEngel** [comment]
"If I want to remove the FanControl software (for resetting behaviour for example) I have to go into windows safemode because there is one file in register I think that is always running and can't normally be deleted."

First, I want to say that I'm a big fan of FanControl. Keep up the good work.
I need to completely remove FanControl (temporarily) from my Win11 system but I'm not sure how to uninstall it. I'm use to removing applications/programs using an app's uninstaller or from "Control Panel-->Programs&Features". Any instructions you can provide will be appreciated. Thank you.
