### ISSUE TITLE
Considered open source?

### ISSUE THREAD

**Issue by Richie78321** [Rem0o/FanControl.Releases#89]
This software seems super cool and has proven quite useful. Any chance you'd consider open sourcing it? I'd be happy to contribute to it.

**Comment by nonsenseninja** [comment]
I totally agree. More people contributing to FanControl could really make it so much better. What's being merged would of course still be up to @Rem0o.

**Comment by seiphr** [comment]
I second (or third, I guess) that.  This is a great project and it would be even better if you'd take contributions from the community.  I just downloaded it, noticed a couple of issues with LibreHardwareMonitor, fixed them, set up a pull request and have already integrated my fix for myself into FanControl until the next release.  Is there a reason you haven't open-sourced it like your other projects?

**Comment by Rem0o** [comment]
@seiphr  you answered part of the question by your action with LHB. You swapped the DLL and it just works. The fact that the backend of the application is an unaltered version of an open-source library makes the most common development needs ( hardware support ) open already.

**Comment by Cubox** [comment]
Using LHM is already a great bit of using open source, having FanControl open source as well would be great!

You don't have to, of course, but if that's your intention, you should say it explicitly. There are some projects where the author says "When I'll have cleaned the code I'll open source it", and it's unclear.

You can also share the source while not making it "open", keeping all copyright, or changing later.
It's just that you're halfway there using both open source libs and having a Github page, it feels weird to not share the source as well :P

**Comment by Richie78321** [comment]
@Rem0o 

> You can also share the source while not making it "open", keeping all copyright, or changing later.

This definitely seems like a nice in-between. I understand that open source can feel like "giving all your ownership away," but this could be a reasonable middleground.

**Comment by dyslesiq** [comment]
I was looking to an open-source fan monitor/control software to adapt an old controller card to my needs and FanControl fit perfectly. So I'm adding one more voice in favour of open-sourcing your project.

Aside from potential ownership preferences, one drawback of opening the source is maybe a little more work dealing with pull requests and community management.
But overall, I feel like opening a recent project like this one can only be positive in terms of quality, stability, user base and thus longevity.

**Comment by Cubox** [comment]
There is another peoject that exists and is open source: https://github.com/lich426/FanCtrl

However I like FanControl here better
I don't care if the source is closed for using the product, but I'd love to be able to contribute to it and modify it for myself. I want to add DIMM temperature as a sensor source, and tinkering with the code would allow me to test that out. Also creating my own logic for fan control. Being able to code directly instead of using the "Mix" fan control logic would be faster for me with some things

**Comment by xcasxcursex** [comment]
+1
This is an application which is granted admin permissions and has access to hardware at a low enough level to destroy your PC. Now, I fully understand that the admin rights and hardware control are handled by the external libs, but that doesn't actually change the previous statement. There is a risk present. 

Having source code available would allow prospective users to confirm that the software is trustworthy with such great power.

**Comment by Cubox** [comment]
Even if the lib is open source, if the software calling it is making my AIO pump shut off, I'll have problems.

**Comment by Richie78321** [comment]
Regardless of what you decide I really appreciate the work you've put into this application! It's so great.

**Comment by jgkawell** [comment]
I second what everyone else here has already said. Making the project open source is only beneficial. It allows for community improvement, gives prospective users a peak under the hood to be sure nothing is off, and depending on the license control of the code can still be maintained by @Rem0o. I really love this project and really want to see how it works under the hood (for both security and improvement).

**Comment by Rem0o** [comment]
A few things here:

1) FanControl is my baby. It's a personal project that is meant to be fun. It just so happened that I'm sharing and improving it for the general public. I want to keep it fun, and ownership is a big part of the fun.

2) There is already a similar software with the same backend as @Cubox mentioned here https://github.com/lich426/FanCtrl
Nobody contributes to it. People could start improving the UI and such for everybody to enjoy, but nobody does. It gets forked and forgotten, why would this be any different for FanControl? 

3) How do you manage ownership of a donationware with built-in donation links when its source is open?  

4) If you want to improve hardware support, like @Cubox  mentionned, adding DIMM temp support, **you can already**.  Simply branch LHM and add the sensor there, FanControl will pick it up.

5) As for risk/vulnerabilities, well nobody is forcing you to trust this software/me. Again, all the low-level stuff is handled by LHM, which is open.

6) What's left for this software to open-source really is the UI and the basic WPF app MVVM structure, with serialization/deserialization and the fan curves logic, which is basic and cookie-cutter. There is no magic or secret sauce here. The only real magic for FanControl if there is any (personal opinion), is coherent software design with focused intentions and features. I don’t think open sourcing would contribute to enhance that aspect, quite the opposite.

**Comment by Cubox** [comment]
Hi, thanks for the reply

For point 4), I am aware. I opened an issue asking for this feature in LHM, since I do not know how I would go about implementing it. I was unsure if the sensor would be picked up by FanControl once added (you are not showing all the sensors LHM is giving, you could have whitelisted the sensors shown in the UI, requiring an update to your code)

**Comment by Richie78321** [comment]
> A few things here:
> 
> 1. FanControl is my baby. It's a personal project that is meant to be fun. It just so happened that I'm sharing and improving it for the general public. I want to keep it fun, and ownership is a big part of the fun.
> 2. There is already a similar software with the same backend as @Cubox mentioned here https://github.com/lich426/FanCtrl
>    Nobody contributes to it. People could start improving the UI and such for everybody to enjoy, but nobody does. It gets forked and forgotten, why would this be any different for FanControl?
> 3. How do you manage ownership of a donationware with built-in donation links when its source is open?
> 4. If you want to improve hardware support, like @Cubox  mentionned, adding DIMM temp support, **you can already**.  Simply branch LHM and add the sensor there, FanControl will pick it up.
> 5. As for risk/vulnerabilities, well nobody is forcing you to trust this software/me. Again, all the low-level stuff is handled by LHM, which is open.
> 6. What's left for this software to open-source really is the UI and the basic WPF app MVVM structure, with serialization/deserialization and the fan curves logic, which is basic and cookie-cutter. There is no magic or secret sauce here. The only real magic for FanControl if there is any (personal opinion), is coherent software design with focused intentions and features. I don’t think open sourcing would contribute to enhance that aspect, quite the opposite.

This sums it up! Thanks for your patience with this issue and thanks for the awesome software!

**Comment by xcasxcursex** [comment]
>     1. ownership is a big part of the fun.

Open sourcing does not effect ownership. Since you'd still be the owner you'd be able to stop anything you didn't find fun. Like if you got tired of pull requests, just don't allow them. Literally nothing has to change from your perspective, to make this software better for all the people who want to use it. 


>     2\. There is already a similar software .... why would this be any different for FanControl?

Would you need it to be different?


>     3\.  How do you manage ownership of a donationware with built-in donation links when its source is open?

The same as ever? This wouldn't change at all.



>     5\. nobody is forcing you to trust this software

Correction: Nobody is _allowing_ us to trust it. We want to, but we can't, because we don't _know_ what it does. Don't take it personally it's just how it is.




It seems to me that you've got the impression that allowing people to view the source code of this application is somehow going to have this huge effect on you and the software. I don't know what gave you that impression, but the only difference you need to experience is nothing at all, since the only difference would be that some random guy is reading something and you don't even know it.

**Comment by Cubox** [comment]
Rem0o has given an answer. Let's not push him more on that. It's his decision, and his only. The fact the software is free to use for us is already huge. We don't want to discourage the openness Rem0o has with the software, allowing issues to be opened publicly to continue.
Having your software issues on Github should not subject you to pressure to open source the software. It'll only discourage people to do it more.

**Comment by xcasxcursex** [comment]
He gave an answer but it needed some correction. I'm not pushing remoo, if he doesn't want to open source it he doesn't have to, it's simple. But just as you want this software to remain free of charge, I'd like open sourcing to remain free of myths of downsides it doesn't have. Besides, perhaps if remoo realised that opens-sourcing is not what he thinks, then he would not mind doing it.

**Comment by snekbaev** [comment]
@xcasxcursex agreed. At least some of us would have had an option to download the sources and built locally vs running provided unsigned executable with admin privileges not to mention setting up automated cloud builds from sources and providing SHAs if needed. Also desktop app devs might have certain ideas on improving the memory footprint of the app when it's minimized to tray. Not complaining, but 146MB seems a bit a lot.

**Comment by Cubox** [comment]
> @xcasxcursex agreed. At least some of us would have had an option to download the sources and built locally vs running provided unsigned executable with admin privileges not to mention setting up automated cloud builds from sources and providing SHAs if needed. Also desktop app devs might have certain ideas on improving the memory footprint of the app when it's minimized to tray. Not complaining, but 146MB seems a bit a lot.

This was settled, no point in bringing it up again.
I love the software, and I would hate for our discussion about open sourcing it make Rem decide to stop sharing it for free.
If you're not happy, don't use it. I'd rather have this than going back to Asus's terrible fan control software. This one is less open source and quite worse.

**Comment by snekbaev** [comment]
@Cubox earlier I've found project issues where author has mentioned something along the lines of "at least not now" moreover, @xcasxcursex has addressed author's concerns quite well, imho. 

>I love the software, and I would hate for our discussion about open sourcing it make Rem decide to stop sharing it for free.

highly doubt author will stop sharing it for free just because of this conversation. There's bunch of utilities which are open source and free + have an optional very cheap personal license to support the software if one likes it. This app seems to be on a similar track with the exception of UI part being closed source (sort of).

> If you're not happy, don't use it. I'd rather have this than going back to Asus's terrible fan control software. This one is less open source and quite worse.

difference is Asus's solution comes from, well, Asus and it is signed, if I would have to choose I'd go with Asus just because of that. Say, somebody would craft a better UI and adds some features, then gives you an executable which is unsigned and requires admin privileges, i.e. from your point of view it's just an app downloaded from the Internet posted by somebody, would you run it on your computer(s) and leave it 24/7? If yes - that's the difference between us. Now you may think, wait a minute, how do you know about the memory footprint then, you must have run it? Yes I did, but before I quickly looked inside the executable (for educational purposes only) as it's not a black box as you may think, quite the opposite I'd say. Anyway, main takeaway: in this particular case, being closed source, imho, doesn't really do much to protect the source code if that's the goal, but creates obstacles for building the project locally and/or submitting PRs. In the end - yes, it's up to the author to decide what direction to take.

**Comment by quinndiggity** [comment]
Fixed in https://github.com/Rem0o/FanControl.Releases/pull/1629

**Comment by wiiznokes** [comment]
Hi, I made an open source alternative [here](https://github.com/wiiznokes/LibreFanControl) for those interested. Works also on Linux.
