### ISSUE TITLE
GPU at 30% although curve should "force" it to 0%

### ISSUE THREAD

**Issue by jonalange** [Rem0o/FanControl.Releases#901]
The system I'm talking about has a RTX 3070 Ti Founders Edition in it.
I set up Fan Control with a curve that depends on the GPU temperature to only start the fans of the GPU at 50°C. Below that the fans should be off completely.

Even though the temp is below my threshold (see my screenshot), the GPU fan is stuck at 30%.

When I disable and reenable the toggle next to the GPU to follow my curve it's working again and the fan turns off.

The problem now is, when the GPU goes above my threshold for 0% it won't go down to 0% anymore even though the temp is fine. It will stay at 30%.

So GPU at 40°C = 0% goes up to 70°C fan goes up to let's say 60% -> GPU cools down again to 40°C fan is stuck at 30% although my curve says it should have 0%.

Any ideas?

Thanks!

![](https://cdn.discordapp.com/attachments/655833355128012830/990962762022785054/unknown.png)

If that's relevant, the other specs of the PC:
MSI B550 A Pro
Ryzen 5 5600X

**Comment by Rem0o** [comment]
The current API I'm using limits to 30% for newer models.

**Comment by ItamarMM** [comment]
> The current API I'm using limits to 30% for newer models.

I think that maybe in this case some solution should be thought around this. Maybe disabling the fan control until certain temperature that the user specifies, (or directly the one in which by default the gpu starts the fans), or using other API if possible.

**Comment by Rem0o** [comment]
@ItamarMM 
![image](https://user-images.githubusercontent.com/14118956/210120028-11c3ed54-7ca9-4494-baab-6c38017b9a35.png)

**Comment by ItamarMM** [comment]
> @ItamarMM ![image](https://user-images.githubusercontent.com/14118956/210120028-11c3ed54-7ca9-4494-baab-6c38017b9a35.png)
While It seemed to be working fine sometimes it will launch at 30%.

I tried disabling Nvidia 0% hardware curve override and enabling It, no luck, still at 30%, tried Exiting the program and opening it again, no luck. Tried restarting the PC, no luck.

![image](https://user-images.githubusercontent.com/59228534/218291526-cd750f7f-18ac-422d-92c6-789e134f770b.png)

**Comment by Rem0o** [comment]
Do you got multiple monitors? Under a certain load or power consumption, certains gpus just won't ever go to 0 rpm.

**Comment by ItamarMM** [comment]
If I exit the program the gpu will instantly go to 0 rpm

**Comment by Rem0o** [comment]
From your screenshot we can't see the "GPU" fan curve.

**Comment by ItamarMM** [comment]
The thing is, I wanted to send you a screenshot today since yesterday I just went to sleep but today It just worked. Yesterday, at 30ºC or so, It was at 30% rpm. I will send you screenshots when this happens again to me, which will probably happen soon, since I have already been on this weird place. 
![image](https://user-images.githubusercontent.com/59228534/218306301-ebe89d7d-6833-46e7-b3d5-0ec8af5ea5c0.png)



After updating BIOS & chipset drivers on Windows... 
![image](https://user-images.githubusercontent.com/59228534/218306314-9b7b15a9-df70-498e-9b11-ceb359695f51.png)

Note: I don't think that updating BIOS or chipset made it work again by itself, because, other times, just updating NVIDIA drivers broke the 0% rpm override, I am kinda lost here.
And It started working correctly again after a minute or so while writing this message. 
![image](https://user-images.githubusercontent.com/59228534/218306333-c3accb0d-1fc4-4f6f-8547-e685ae99f7c4.png)

Maybe the Nvidia 0% hardware curve override is delayed in some way? This is so random.

**Comment by Rem0o** [comment]
You have to understand how the "override" works.  Basically, when FanControl ask for 0%, it will basically let go of the GPU fans and let it manage itself as if FanControl was closed. In other words, It's the "native" behavior of your GPU you are getting.  If that native behavior happens to be 0% at that state, then great!  BUT, it might not be, depending on what are the conditions required for your GPU to go 0 rpm.

**Comment by rubik31** [comment]
> You have to understand how the "override" works. Basically, when FanControl ask for 0%, it will basically let go of the GPU fans and let it manage itself as if FanControl was closed. In other words, It's the "native" behavior of your GPU you are getting. If that native behavior happens to be 0% at that state, then great! BUT, it might not be, depending on what are the conditions required for your GPU to go 0 rpm.

This cant be the case. while using the override feature, It initially works for like 2 minutes, then it jumps to 30%. toggling off control of GPU, or just closing fan control returns the GPU fans to 0% instantly meaning that fancontrol doesnt seem to be letting go of the GPU properly. If it was it wouldnt keep jumping to 30% because If fancontrol wasnt open my GPU would be sitting at 0% (until a certain temperature built in to the GPU).

**Comment by Rem0o** [comment]
@rubik31 

Some infos are still missing.

1. Are you using the NvAPIWrapper provider in sensor settings?
2. Disable force apply on both your GPU controls
3. Set your stop % as 30 and your Start% at 32 for both GPU controls.

**Comment by rubik31** [comment]
> @rubik31
> 
> Some infos are still missing.
> 
> 1. Are you using the NvAPIWrapper provider in sensor settings?
> 2. Disable force apply on both your GPU controls
> 3. Set your stop % as 30 and your Start% at 32 for both GPU controls.

yes I have the NvAPIWrapper, but disabling force apply fixed my issue it seems, idk why i didnt think to try that but thanks for the help.

**Comment by kc-dustinkasel** [comment]
I have the same issue, in my case I'm just running in manual control mode. I have enabled NvAPIWrapper, disabled force apply, and set the command % to 0. I can see it briefly jump down but then is quickly overridden back to 30%.
